//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Alert.rc
//
#define IDD_ALERT_DIALOG                102
#define IDR_MAINFRAME                   128
#define IDC_CURTIME                     1000
#define IDC_RESTTIME                    1001
#define IDC_INTERVAL                    1002
#define IDC_SPIN                        1003
#define IDC_APPLY                       1005
#define IDC_HIDE                        1006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1007
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
