Dim app

On Error Resume Next

Set app = Nothing

Set app = GetObject( , "MSDev.Application")

If Not app Is Nothing Then

	MsgBox app.Name & " " & app.Version & " is running" & vbCrLf & vbCrLf &_
	"Current project: " & app.ActiveProject.Name & vbCrLf &_
	"Project type: " & app.ActiveProject.Type, vbInformation, "Info"

	Set app = Nothing

Else

	MsgBox "Application is not running!", vbCritical, "Error"

End If