#if !defined(AFX_WMPERRORITEM_H__8F8DC334_FEAB_44F3_85DA_6EF2528DA05F__INCLUDED_)
#define AFX_WMPERRORITEM_H__8F8DC334_FEAB_44F3_85DA_6EF2528DA05F__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CWMPErrorItem wrapper class

class CWMPErrorItem : public COleDispatchDriver
{
public:
	CWMPErrorItem() {}		// Calls COleDispatchDriver default constructor
	CWMPErrorItem(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CWMPErrorItem(const CWMPErrorItem& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetErrorCode();
	CString GetErrorDescription();
	VARIANT GetErrorContext();
	long GetRemedy();
	CString GetCustomUrl();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_WMPERRORITEM_H__8F8DC334_FEAB_44F3_85DA_6EF2528DA05F__INCLUDED_)
