# Sample Makefile for PDFlib's Ruby binding
# $Id: Makefile.sample,v 1.1.2.1 2005/12/06 15:20:01 rjs Exp $


RUBYBIN = ruby

all: test

test::
	-$(RUBYBIN) hello.rb
	-$(RUBYBIN) image.rb
	-$(RUBYBIN) pdfclock.rb
	-$(RUBYBIN) chartab.rb
	-$(RUBYBIN) invoice.rb
	-$(RUBYBIN) businesscard.rb
