/*! Copyright 2013 Baidu Inc. All Rights Reserved. */;(function(){var m=void 0,n=!0,o=null,q=!1,s="BAIDU_DUP_require",u="BAIDU_DUP_define",v=["search!"],w=3,y=document,z={},A=0,B=1,C=2,D=3,E=4,F=5;function G(a){var c=H(a),d=c[0],c=c[1];this.id=a;this.name=c;this.uri=I(c);this.ga=!c;this.status=A;d&&c&&(this.ka=J(K(d+"!"))||{load:function(){}});this.o=[]}var Q=window[s]||function(a,c,d){L(a,function(){for(var b=[],f=0;f<a.length;f++)b[f]=J(K(a[f]));P(c)&&c.apply(window,b)},d)};
function L(a,c,d){var b=a.length;if(0===b)c();else for(var f=b,e=0;e<b;e++)(function(a){function h(){if(a.status<C)b();else{for(var h=a.o,f=[],c=0;c<h.length;c++){var t=h[c];t&&K(t).status<D&&f.push(t)}0===f.length?b():L(f,b,d)}}function b(){a&&a.status<D&&(a.status=D);0===--f&&c()}var e=a.ka;e&&(e.normalize&&(a.name=e.normalize(a.name,I)),e.name2url&&(a.uri=e.name2url(a.name)));a.status<C?e&&P(e.load)?e.load(a.name,Q,function(h){R(a.id,[],function(){return h});b()}):S(a,h,d):h()})(K(a[e]))}
var T={},U={},V={};function S(a,c,d){a.status=B;V[a.id]?c():U[a.id]?T[a.id].push(c):(U[a.id]=n,T[a.id]=[c],d?(c=a.uri,a=y.createElement("script"),a.charset="utf-8",a.async=n,a.src=c,c=y.getElementsByTagName("head")[0]||y.body,c.insertBefore(a,c.firstChild)):y.write('<script charset="utf-8" src="'+a.uri+'"><\/script>'))}var R=window[u]||function(a,c,d){var b=K(a);b.status<C&&(b.o=c,b.factory=d,b.status=b.ga?D:C);if(U[a]){delete U[a];V[a]=n;c=T[a];for(delete T[a];a=c.shift();)a()}};
function J(a){if(!a)return o;if(a.status>=E)return a.J;if(a.status<D&&a.J===m)return o;a.status=E;for(var c=[],d=0;d<a.o.length;d++)c[d]=J(K(a.o[d]));var b=d=a.factory;P(d)&&(b=d.apply(window,c));a.status=F;return a.J=b}function I(a){return/^https?:\/\//.test(a)?a:"http://dup.baidustatic.com/painter/"+a+".js"}function K(a){return z[a]||(z[a]=new G(a))}function H(a){var c,d=a?a.indexOf("!"):-1;-1<d&&(c=a.slice(0,d),a=a.slice(d+1,a.length));return[c,a]}
function P(a){return"[object Function]"===Object.prototype.toString.call(a)}
R("util/lang",[],function(){function a(a){for(var b={},f="Array Boolean Date Error Function Number RegExp String".split(" "),c=0,g=f.length;c<g;c++)b["[object "+f[c]+"]"]=f[c].toLowerCase();return a==o?"null":b[Object.prototype.toString.call(a)]||"object"}var c=Object.prototype.hasOwnProperty;return{z:c,b:a,getAttribute:function(a,b){for(var f=a,c=b.split(".");c.length;){if(f===m||f===o)return;f=f[c.shift()]}return f},P:function(d){if("object"!==a(d))return"";var b=[],f;for(f in d)c.call(d,f)&&b.push(f+
"="+encodeURIComponent(d[f]));return b.join("&")},i:function(c){var b=[];switch(a(c)){case "object":b=Array.prototype.slice.call(c);break;case "array":b=c;break;case "number":case "string":b.push(c)}return b},unique:function(a){for(var b=[],c={},e=a.length,g=0;g<e;g++){var h=a[g];c[h]||(b[b.length]=h,c[h]=n)}return b},removeItem:function(a,b){for(var c=[].slice.call(a),e=c.length-1;0<=e;e--)c[e]===b&&c.splice(e,1);return c},B:function(){}}});
R("util/browser",["util/lang"],function(a){var c={},d=navigator.userAgent,b=window.RegExp;/msie (\d+\.\d)/i.test(d)&&(c.M=document.documentMode||+b.$1);/opera\/(\d+\.\d)/i.test(d)&&(c.opera=+b.$1);/firefox\/(\d+\.\d)/i.test(d)&&(c.sa=+b.$1);/(\d+\.\d)?(?:\.\d)?\s+safari\/?(\d+\.\d+)?/i.test(d)&&!/chrome/i.test(d)&&(c.Ea=+(b.$1||b.$2));if(/chrome\/(\d+\.\d)/i.test(d)){c.V=+b.$1;var f;try{f="scoped"in document.createElement("style")}catch(e){f=q}f&&(c.pa=n)}try{/(\d+\.\d)/.test(a.getAttribute(window,
"external.max_version"))&&(c.Ba=+b.$1)}catch(g){}a="Android iPad iPhone Linux Macintosh Windows".split(" ");b="";for(f=0;f<a.length&&!(b=a[f],d.match(RegExp(b.toLowerCase(),"i")));f++);c.platform=b;return c});
R("util/dom",["util/lang"],function(a){function c(a){try{if(a&&"object"===typeof a&&a.document&&"setInterval"in a)return n}catch(b){}return q}function d(a,b){b=2===arguments.length?b:a.parent;return a!=b||!c(a)}function b(a){return 9===a.nodeType?a:a.ownerDocument||a.document}return{c:function(b,c){return"string"===a.b(b)?(c||window).document.getElementById(b):b.nodeName&&(1===b.nodeType||9===b.nodeType)?b:o},ha:c,l:d,k:function(a,b){for(var b=2===arguments.length?b:a.parent,c=0;10>c++&&d(a,b);){var h;
try{h=!!a.parent.location.toString()}catch(j){h=q}if(!h)return n;a=a.parent}return 10<=c?n:q},$:b,t:function(a){a=b(a);return a.parentWindow||a.defaultView||o},n:function(a){a=c(a)?a.document:b(a);return"CSS1Compat"===a.compatMode?a.documentElement:a.body}}});
R("util/style",["util/lang","util/dom","util/browser"],function(a,c,d){function b(a,b){if(!a)return"";var d="",d=-1<b.indexOf("-")?b.replace(/[-][^-]{1}/g,function(a){return a.charAt(1).toUpperCase()}):b.replace(/[A-Z]{1}/g,function(a){return"-"+a.charAt(0).toLowerCase()}),e=c.t(a);if(e&&e.getComputedStyle){if(e=e.getComputedStyle(a,o))return e.getPropertyValue(b)||e.getPropertyValue(d)}else if(a.currentStyle)return e=a.currentStyle,e[b]||e[d];return""}function f(a){var j={top:0,left:0};if(a===c.n(a))return j;
var d=c.$(a),e=d.body,d=d.documentElement;a.getBoundingClientRect&&(a=a.getBoundingClientRect(),j.left=Math.floor(a.left)+Math.max(d.scrollLeft,e.scrollLeft),j.top=Math.floor(a.top)+Math.max(d.scrollTop,e.scrollTop),j.left-=d.clientLeft,j.top-=d.clientTop,a=b(e,"borderLeftWidth"),e=b(e,"borderTopWidth"),a=parseInt(a,10),e=parseInt(e,10),j.left-=isNaN(a)?2:a,j.top-=isNaN(e)?2:e);return j}function e(a,c){var d=b(a,"margin"+c).toString().toLowerCase().replace("px","").replace("auto","0");return parseInt(d,
10)||0}function g(b){for(var j=c.t(b),e=100;b&&b.tagName;){var g=100;if(d.M){if(5<d.M)try{g=parseInt(a.getAttribute(b,"filters.alpha.opacity"),10)||100}catch(f){}e=e>g?g:e}else{try{g=100*(j.getComputedStyle(b,o).opacity||1)}catch(p){}e*=g/100}b=b.parentNode}return 0===e?0:e||100}return{za:b,ya:f,w:function(a){var b=c.c(a);if(!b)return q;a=f(b);b=c.t(b);if(!b)return a;for(var e=0;b!==b.parent&&10>e++&&!c.k(b)&&b.frameElement;){var d=f(b.frameElement);a.left+=d.left;a.top+=d.top;b=b.parent}return a},
ta:e,xa:function(a,b){var d=c.c(a),g=d.offsetWidth;b&&(g+=e(d,"Left")+e(d,"Right"));return g},wa:function(a,b){var d=c.c(a),g=d.offsetHeight;b&&(g+=e(d,"Top")+e(d,"Bottom"));return g},va:g,ua:function(a){for(var b=c.c(a),a=c.t(b),b=g(b),d=0;10>d++&&c.l(a)&&!c.k(a);){var e=a.frameElement?g(a.frameElement):100,b=b*(e/100);a=a.parent}return b},ea:function(a){return c.n(a||window).scrollWidth||-1},da:function(a){return c.n(a||window).scrollHeight||-1},r:function(a){return c.n(a||window).clientWidth||
-1},q:function(a){return c.n(a||window).clientHeight||-1}}});R("util/event",["util/dom"],function(a){return{bind:function(c,d,b){if(c=a.ha(c)?c:a.c(c))if(c.addEventListener)c.addEventListener(d,b,q);else if(c.attachEvent)c.attachEvent("on"+d,b);else{var f=c["on"+d];c["on"+d]=function(){f&&f.apply(this,arguments);b.apply(this,arguments)}}return c}}});
R("util/cookie",["util/lang"],function(a){return{get:function(a,d){var b=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie);return b?d?decodeURIComponent(b[2]):b[2]:""},set:function(c,d,b,f){var e=b.expires;"number"===a.b(e)&&(e=new Date,e.setTime(+e+b.expires));document.cookie=c+"="+(f?encodeURIComponent(d):d)+(b.path?"; path="+b.path:"")+(e?"; expires="+e.toGMTString():"")+(b.domain?"; domain="+b.domain:"")}}});
R("util/data",["util/lang"],function(a){function c(b,c){var d=c;switch(a.b(b)){default:d=q;break;case "string":var j=b.split(".");if(1<j.length)for(var i=f;j.length;){var k=j.shift();i[k]=j.length?i[k]?i[k]:{}:c;i=i[k]}else f[b]=c}return d}function d(b){var c=q;switch(a.b(b)){case "string":c=a.getAttribute(f,b)}return c}function b(a,b,h){if(!a||!b)return q;var j=d(a)||{};switch(h){case "+1":h=j[b]||0;j[b]=++h;break;default:j[b]=parseInt(h,10)}c(a,j);return j[b]}var f={};return{j:function(a,b){var c=
window;return c[a]?c[a]:c[a]=b},L:function(a){var b=window,c=b[a];b[a]=m;return c},C:c,g:d,H:function(a,c){return b(a,c,"+1")},Ca:function(a,c,d){return b(a,c,d)},count:b,Z:function(a,b){return!a||!b?q:(d(a)||{})[b]||0},oa:function(a,b){if(!a||!b)return q;var h=d("pageConfig")||{};h[a]=b;c("pageConfig",h);return n},Y:function(a){return!a?q:(d("pageConfig")||{})[a]}}});
R("util/storage",[],function(){function a(a,b){if(c){var f=c.getItem(a);return b&&f?decodeURIComponent(f):f}return o}var c=window.localStorage;return{getItem:a,S:function(d,b,f){if(c){b=f?encodeURIComponent(b):b;f=a(d)||"";try{c.setItem(d,f+((f&&"|")+b))}catch(e){}}},R:function(d,b,f){if(c)if(b=f?encodeURIComponent(b):b,f=a(d)||"",f=f.replace(RegExp(b+"\\|?","g"),"").replace(/\|$/,""))try{c.setItem(d,f)}catch(e){}else c.removeItem(d)}}});
R("util/log",["util/lang","util/event","util/storage"],function(a,c,d){function b(a,b){var c=new Image,d="BAIDU_DUP_log_"+Math.floor(2147483648*Math.random()).toString(36);window[d]=c;c.onload=c.onerror=c.onabort=function(){c.onload=c.onerror=c.onabort=o;c=window[d]=o;b&&b(f,a,n)};c.src=a}var f="BAIDU_DUP_log_storage";return{Aa:b,Da:function(){var a=d.getItem(f);if(a)for(var a=a.split("|"),c=0,h=a.length;c<h;c++)b(decodeURIComponent(a[c]),d.R)},D:function(e){var e="object"===a.b(e)?e:{},g=e.url||
"http://cbjslog.baidu.com/log",h=e.option||"now",e=a.P(e.data||{}),g=g+((0<=g.indexOf("?")?"&":"?")+e+(e?"&":"")+"rdm="+ +new Date);switch(h){case "now":b(g);break;case "block":break;default:d.S(f,g,n),c.bind(window,"unload",function(){b(g,d.R)})}}}});R("util","util/lang,util/dom,util/style,util/event,util/cookie,util/data,util/storage,util/log,util/browser".split(","),function(a,c,d,b,f,e,g,h,j){return{lang:a,a:c,style:d,event:b,cookie:f,data:e,Fa:g,log:h,U:j}});
R("biz",["util"],function(a){function c(a){var b={},d="",e=window;try{d=e.top.location.search,"string"!==typeof d&&(d=e.location.search)}catch(f){d=e.location.search}d=d||"";0===d.indexOf("?")&&(d=d.substring(1));d=d.split("&");for(e=0;e<d.length;e++){var l=d[e].split("=");b[l[0]]=l[1]}c=function(a){return b[a]};return b[a]}function d(b,c){var d=/^[0-9a-zA-Z]+$/;return!b||!d.test(b)||!c?[]:c="array"===a.lang.b(c)?c:Array.prototype.slice.call(arguments,1)}function b(b,c,d){if(!c||!c.length)return q;
var d=d||{G:q,N:q,O:q},i=d.N?a.data.g(f):{},k=d.G?e:f,i=d.O?{}:a.data.g(k)||i,d={},l;for(l in i)a.lang.z.call(i,l)&&(d[l]="array"===a.lang.b(i[l])?i[l].slice():i[l]);var i=d[b]||[],p=c.length;for(l=0;l<p;l++){var t=c[l];"string"===typeof t&&(t=encodeURIComponent(t),100>=t.length&&(i[i.length]=t))}if(!i.length)return q;d[b]=a.lang.unique(i);a.data.C(k,d);return n}var f="bizOrientations",e="bizUrgentOrientations";return{ca:c,I:function(a,c){var e=d.apply(this,arguments);return b(a,e)},T:function(a,
c){var e=d.apply(this,arguments);return b(a,e,{G:n,N:n})},qa:function(a,c){var e=d.apply(this,arguments);return b(a,e,{G:n,O:n})},ba:function(b){var b=Math.max(0,Math.min(b||500,500)),c=[],d=a.data.g(e)||a.data.g(f)||{};if("object"===a.lang.b(d))for(var i in d)a.lang.z.call(d,i)&&(c[c.length]=i+"="+d[i].join(","));a.data.C(e,m);c.sort(function(a,b){return a.length-b.length});d="";i=c.length;for(var k=0;k<i&&!(d.length+c[k].length>=b);k++)d+=(k?"&":"")+c[k];return d}}});
R("preview",["biz"],function(a){function c(){var c=a.ca,b=c("baidu_clb_preview_sid")||c("baidu_dup_preview_sid"),f=c("baidu_clb_preview_mid")||c("baidu_dup_preview_mid"),e=c("baidu_clb_preview_vc")||c("baidu_dup_preview_vc"),c=+c("baidu_clb_preview_ts")||+c("baidu_dup_preview_ts");return 3E4>=+new Date-c?{Q:b,ia:f,ra:e}:o}return{fa:function(a){var b=[],f=c();f&&a==f.Q&&(b.push("mid="+f.ia),b.push("sid="+f.ra));return b.join("&")},g:c}});
R("slot",["util"],function(a){function c(){for(var a={response:{},holder:"",stack:[],errors:[],status:{}},b=j.length-1;0<=b;b--)a.status[j[b]]=0;return a}function d(a,b){var c=q;"fillAsync"===b&&(c=n);l[a]&&-1!==l[a].stack.join(" ").toLowerCase().indexOf("async")&&(c=n);return c}function b(a,b){if(!a)return"";var c=p+a;b&&(c+="_"+b);return c}function f(a,b,c){if(!a||!b)return q;c===m&&(c=+new Date);return l[a]?(l[a].status[b]=c,n):q}function e(a,b){g(a,"errors",b)}function g(b,c,d){b&&c&&d&&(b=l[b])&&
"array"===a.lang.b(b[c])&&b[c].push(d)}function h(a){return!a?l:l[a]||q}var j="add,create,request,response,render,finish".split(","),i=[],k={},l={},p="BAIDU_DUP_wrapper_";return{add:function(){var b={ids:[],preloadIds:[]},d=a.lang.i(arguments);if(!d.length)return b;for(var d=d.join(",").split(","),e=[],j=[],g=d.length,p=0;p<g;p++){var r=d[p];if(k.hasOwnProperty(r)){var N=r+"_"+k[r],x=h(N).stack||[];if("preload"===x[x.length-1]){b.preloadIds.push(N);continue}k[r]+=1}else k[r]=0;r=r+"_"+k[r];l[r]=new c;
f(r,"add");j.push(r);e.push(r)}i=i.concat(j);b.ids=e;return b},create:function(c,M,h){if(!c||!M)return q;var j=b(c),g=n;if(a.a.c(j))return l[c].holder=j,g;if(d(c,M)){h=h||"";l[c].holder=h;h=a.a.c(h);try{h&&(h.innerHTML='<div id="'+j+'"></div>',l[c].holder=j)}catch(i){e(c,"Failed to insert wrapper"),g=q}}else if(document.write('<div id="'+j+'"></div>'),!a.a.c(j))try{var k=document.getElementsByTagName("script"),p=k[k.length-1];if(p){var x=p.parentNode;if(x){var O=document.createElement("div");O.id=
b(c,"b");x.insertBefore(O,p)}}}catch(W){e(c,"Failed to create backup wrapper")}f(c,"create");return g},W:d,aa:function(a){return d(a)?"async":"sync"},K:function(c){return!c?"":(c=a.a.c(l[c].holder)||a.a.c(b(c))||a.a.c(b(c,"b")))&&c.id||""},s:h,F:function(a,b){if(!a||!b)return q;return l[a]?(l[a].response=b,f(a,"response"),n):q},m:f,h:e,u:function(a,b){g(a,"stack",b)},v:function(b){b=a.lang.i(b);if(!b.length)return q;var c=[],d={},e;for(e=0;e<i.length;e++)d[i[e]]=e+1;for(e=0;e<b.length;e++){var f=
d[""+b[e]];f===m&&(f=0);c.push(f)}return c},w:function(c){c=a.lang.i(c);if(!c.length)return["-1x-1"];for(var d=[],f=0;f<c.length;f++){var h=c[f],j;try{var g=a.a.c(b(h))||a.a.c(b(h,"b"));if(g){var i=a.style.w(g);i&&(j=[i.top,i.left])}}catch(k){e(h,"Unable to get ps")}j=j?j:[-1,-1];d.push(j.join("x"))}return d}}});
R("api",["slot","util"],function(a,c){return{getDai:a.v,getSlots:a.s,getFillType:a.aa,getFillWrapperId:a.K,setStatus:a.m,addErrorItem:a.h,addStackItem:a.u,bind:c.event.bind,getType:c.lang.b,noop:c.lang.B,sendLog:c.log.D,putInfo:c.data.C,getInfo:c.data.g,defineOnce:c.data.j,addCount:c.data.H,getCount:c.data.Z,getConfig:c.data.Y}});
R("param",["slot","preview","biz","util"],function(a,c,d,b){function f(a,b){for(var b=b||0,c=[],d=0,e=a.length;d<e;d++)c.push(a[d].split("_")[b]);return c.join(",")}function e(a){a=a||window.document.domain;0===a.indexOf("www.")&&(a=a.substr(4));"."===a.charAt(a.length-1)&&(a=a.substring(0,a.length-1));var b=a.match(RegExp("([a-z0-9][a-z0-9\\-]*?\\.(?:com|cn|net|org|gov|info|la|cc|co|jp|us|hk|tv|me|biz|in|be|io|tk|cm|li|ru|ws|hn|fm|tw|ma|in|vn|name|mx|gd|im)(?:\\.(?:cn|jp|tw|ru|th))?)$","i"));return b?
b[0]:a}var g=window,h=g.document,j=g.screen,i=g.navigator,k=+new Date,l,p=[{key:"di",value:function(a){return f(a.id)}},{key:"dcb",value:function(){return"BAIDU_DUP_define"}},{key:"dtm",value:function(){return"BAIDU_DUP_SETJSONADSLOT"}},{key:"dbv",value:function(){var a=b.U;return a.pa?"1":a.V?"2":"0"}},{key:"dci",value:function(b){for(var c="-1",d={fill:"0",fillOnePiece:"1",fillAsync:"2",preload:"3"},e=0;e<b.id.length;e++){var f=a.s(b.id[e]);if(f){var f=f.stack,h=f.length;if(1<=h){c=d[f[h-1]];break}}}return c}},
{key:"dri",value:function(a){return f(a.id,1)}},{key:"dis",value:function(){var a=0;b.a.l(g)&&(a+=1);b.a.k(g,g.top)&&(a+=2);var c=b.style.r(),d=b.style.q();if(40>c||10>d)a+=4;return a}},{key:"dai",value:function(b){return a.v(b.id).join(",")}},{key:"dds",value:function(){var a=b.data.g("dds");return b.lang.P(a)}},{key:"drs",value:function(){var a={uninitialized:0,loading:1,loaded:2,interactive:3,complete:4};try{return a[h.readyState]}catch(b){return-1}}},{key:"dvi",value:function(){return"7o"}},{key:"ltu",
p:n,value:function(){for(var a=0,c=g,d=0,e=0;10>a++&&b.a.l(c)&&!b.a.k(c,c.parent);){d=b.style.r(c);e=b.style.q(c);if(400<d&&120<e)break;c=c.parent}d="";return d=10<=a||b.a.k(c,c.parent)?c.document.referrer||c.location.href:c.location.href}},{key:"liu",p:n,value:function(){return b.a.l(g)?h.URL:""}},{key:"ltr",p:n,value:function(){for(var a=0,c=g;10>a++&&b.a.l(c)&&!b.a.k(c,c.parent);)c=c.parent;a="";try{a=c.opener?c.opener.document.location.referrer:""}catch(d){}return a||c.document.referrer}},{key:"lcr",
p:n,value:function(){var a=h.referrer,c=a.replace(/^https?:\/\//,""),c=c.split("/")[0],c=c.split(":")[0],c=e(c),d=e(),f=b.cookie.get("BAIDU_DUP_lcr")||b.cookie.get("BAIDU_CLB_REFER",n);if(f&&d===c)return f;return d!==c?(b.cookie.set("BAIDU_DUP_lcr",a,{domain:d}),a):""}},{key:"ps",value:function(b){return a.w(b.id).join(",")}},{key:"psr",value:function(){return[j.width,j.height].join("x")}},{key:"par",value:function(){return[j.availWidth,j.availHeight].join("x")}},{key:"pcs",value:function(){return[b.style.r(),
b.style.q()].join("x")}},{key:"pss",value:function(){return[b.style.ea(),b.style.da()].join("x")}},{key:"pis",value:function(){return(b.a.l(g)?[b.style.r(),b.style.q()]:[-1,-1]).join("x")}},{key:"cfv",value:function(){var a=0;if(i.plugins&&i.mimeTypes.length){var b=i.plugins["Shockwave Flash"];b&&b.description&&(a=b.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")+".0")}else if(g.ActiveXObject&&!g.opera)for(b=10;2<=b;b--)try{var c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+b);
c&&(a=c.GetVariable("$version").replace(/WIN/g,"").replace(/,/g,"."))}catch(d){}return parseInt(a,10)}},{key:"ccd",value:function(){return j.colorDepth||0}},{key:"chi",value:function(){return g.history.length||0}},{key:"cja",value:function(){return i.javaEnabled().toString()}},{key:"cpl",value:function(){return i.plugins.length||0}},{key:"cmi",value:function(){return i.mimeTypes.length||0}},{key:"cce",value:function(){return i.cookieEnabled||0}},{key:"col",value:function(){return(i.language||i.browserLanguage||
i.systemLanguage).replace(/[^a-zA-Z0-9\-]/g,"")}},{key:"cec",value:function(){return(h.characterSet?h.characterSet:h.charset)||""}},{key:"cdo",value:function(){var a=window.orientation;a===m&&(a=-1);return a}},{key:"tsr",value:function(){var a=0,b=+new Date;k&&(a=b-k);return a}},{key:"tlm",value:function(){return Date.parse(h.lastModified)/1E3}},{key:"tcn",value:function(){return Math.round(+new Date/1E3)}},{key:"tpr",value:function(a){var a=a&&a.max_age?a.max_age:24E4,b=+new Date;l?b-l>=a&&(l=b):
l=b;return l||""}},{key:"_preview",value:function(a){return c.fa(f(a.id))}},{key:"baidu_id",value:function(){return b.cookie.get("BAIDUID")}},{key:"_orientation",value:function(){return d.ba()}}];return{get:function(a,b){for(var c=[],d=0,e=p.length;d<e;d++){var f;try{var h=p[d],j=h.key,g=h.p,i=h.value,i="function"===typeof i?i(a):i,i=g?encodeURIComponent(i):i;if(b&&b===j)return i;f=j&&0!==j.indexOf("_")?j+"="+i:i}catch(k){f=encodeURIComponent(k.toString()),f=f.slice(0,100)}f&&c.push(f)}c=c.join("&");
return c.slice(0,2048)}}});
R("request",["param","slot","util"],function(a,c,d){R("request!",[],{name2url:function(b){return"http://cb.baidu.com/ecom?"+a.get({id:b.split(",")})}});R("batch!",[],{name2url:function(b){return"http://cb.baidu.com/ecom?"+a.get({id:b.split(",")})}});return{send:function(a,f,e){if(!a||!f||e===m)return q;var g=[];if("array"!==d.lang.b(a))c.m(a,"request"),g=["request!"+a];else{for(g=0;g<a.length;g++)c.m(a[g],"request");g=1===a.length?["request!"+a[0]]:["batch!"+a.join(",")]}Q(g,f,e);return n}}});
R("control",["slot","request","preview","util"],function(a,c,d,b){function f(c,d,e){var f=d.deps,g=d.data,p=a.K(c);e&&!p?a.h(c,"HolderNotFound"):f&&(0>f[0].indexOf("clb/")&&a.m(c,"finish"),Q(f,function(d){if("object"===b.lang.b(g)){g.id=c;if(d.hasOwnProperty("validate"))try{var e=d.validate(g);e!==n&&b.log.D({data:{type:e||"ResponseError",errorPainter:f[0],id:c,slotType:g._stype,materialType:g._isMlt,html:!!g._html}})}catch(j){a.h(c,"validateException")}if(d.hasOwnProperty("render"))try{a.m(c,"render"),
d.render(g,p)}catch(i){a.h(c,"RenderException")}else a.h(c,"RenderNotFound")}else a.h(c,"ResponseFormatError")},e))}function e(b,d,e){if(!b)return q;var e=e||"",g=a.add(b),b=g.ids[0]||g.preloadIds[0];if(!b)return q;var l=a.W(b,d);a.u(b,d);a.create(b,d,e);g.ids.length?c.send(b,function(c){a.F(b,c);f(b,c,l)},l):g.preloadIds.length&&(d=a.s(b).response,f(b,d,l));return n}function g(b){for(var c=0,d=b+"_"+c;0!==a.v([d])[0];){var e=a.s(d);if((e=e&&e.response)&&0===e.deps[0].indexOf("clb/")){var f=e.data,
e=f._isMlt;(0===e&&""!==f._html||e===q&&f._fxp)&&a.m(d,"finish",0)}d=b+"_"+ ++c}if(b!==m&&(b=(c=window.BAIDU_CLB_SLOTS_MAP)&&c[b],b!==m&&(e=b._isMlt,0===e&&""!==b._html||e===q&&b._fxp)))b._done=q}window.BAIDU_CLB_prepareMoveSlot=g;return{fill:function(a){return e(a,"fill")},X:function(a,b){return e(a,"fillAsync",b)},la:function(){function e(d){c.send(d,function(c){if("array"===b.lang.b(c)){if(c&&c.length===d.length)for(var e=0;e<d.length;e++)a.F(d[e],c[e])}else"object"===b.lang.b(c)&&c&&1===d.length&&
a.F(d[0],c)},q)}var f=b.lang.i(arguments),f=b.lang.unique(f),g=d.g();if(g)for(var k=0,l=f.length;k<l;k++)f[k]==g.Q&&(f.splice(k,1),k--);for(f=a.add(f).ids;f.length;){g=f.splice(0,16);for(k=0;k<g.length;k++)a.u(g[k],"preload");e(g)}},ma:g}});
R("global",["control","biz","util"],function(a,c,d){function b(a){a=a.split(".");return j[a[0]]+a[1]}function f(){var a=h.BAIDU_DUP;if(!("object"===d.lang.b(a)&&a.push)){if("array"===d.lang.b(a)&&a.length)for(var b=0;b<a.length;b++)e(a[b]);h.BAIDU_DUP=m;d.data.j("BAIDU_DUP",{push:e});d.data.j("BAIDU_DUP_proxy",function(a){if(a)return function(){try{return e([a].concat(d.lang.i(arguments)))}catch(b){0<w--&&d.log.D({data:{type:"ExecuteException",errorName:a,args:d.lang.i(arguments).join("|"),isQuirksMode:"CSS1Compat"!==
document.compatMode,documentMode:document.documentMode||"",readyState:document.readyState||"",message:b.message}})}}});for(b in k)b&&d.lang.z.call(k,b)&&d.data.j(b,h.BAIDU_DUP_proxy(b));g()}}function e(a){if("array"!==d.lang.b(a))return q;var b=a.shift();d.data.H("apiCount",b);return(b=k[b]||l[b]||q)&&b.apply(o,a)}function g(){function a(b){for(var c=0,d=v.length;c<d;c++)if(0===b.indexOf(v[c]))return n;return q}d.data.j(s,function(b){for(var c=0,d=b.length;c<d;c++)if(a(b[c]))return;Q.apply(o,arguments)});
d.data.j(u,function(b,c){for(var d=0,e=c.length;d<e;d++)if(a(c[d]))return;R.apply(o,arguments)})}var h=window,j={clb:"BAIDU_CLB_",dan:"BAIDU_DAN_",nova:"cpro"},i=[{e:["clb.fillSlot","clb.singleFillSlot","clb.fillSlotWithSize"],f:["fill"],d:a.fill},{e:["clb.fillSlotAsync"],f:["fillAsync"],d:a.X},{e:["clb.preloadSlots"],f:["preload"],d:a.la},{e:["clb.prepareMoveSlot"],f:["prepareMove"],d:a.ma},{e:["clb.addOrientation"],f:["addOrientation"],d:c.I},{e:["clb.addOrientationOnce"],f:["addOrientationOnce"],
d:c.T},{e:["clb.setOrientationOnce"],f:["setOrientationOnce"],d:c.qa},{e:["clb.setConfig"],f:["putConfig"],d:d.data.oa},{e:["clb.addSlot","clb.enableAllSlots","clb.SETHTMLSLOT"],f:[],d:d.lang.B}],i=function(a){for(var c={},d={},e=0;e<a.length;e++){for(var f=a[e],g=f.e,h=f.f,f=f.d;g.length;)c[b(g.shift())]=f;for(;h.length;)d[h.shift()]=f}return{ja:c,na:d}}(i),k=i.ja,l=i.na;return{A:function(){var e=d.data.L(b("clb.ORIENTATIONS"));if(e)for(var g in e)Object.prototype.hasOwnProperty.call(e,g)&&c.I(g,
e[g]);a.fill(d.data.L(b("clb.SLOT_ID")));f()}}});R("logService",["util/lang","util/event","util/log"],function(a,c){return{A:function(){window.BAIDU_DUP_log_loaded||(window.BAIDU_DUP_log_loaded=n,c.bind(window,"load",function(){Q(["detect"],a.B,n)}))}}});Q(["global"],function(a){a.A()});Q(["logService"],function(a){a.A()});})();
window.BAIDU_DUP_define("detect",["api"],function(f){function g(a){a.url="";a.host=window.location.hostname;a.from="DUP";f.sendLog({data:a,a:"now"})}try{setTimeout(function(){var a=f.getSlots(),d;for(d in a){var b=a[d],c=b.response,e=!1;if("object"!==f.getType(c))e=!0;else{var e=!0,h;for(h in c)if(Object.prototype.hasOwnProperty.call(c,h)){e=!1;break}}var i=b.status,b=b.stack;e?g({type:"preload"===b[0]?"preloadFail":"loadFail",id:d}):!i.render&&!i.finish&&g({type:"renderFail",id:d,error:"preload"===
b[0]?"PreloadNotFilled":"NotFilled",empty:!(!c.data||!c.data._html)})}},0)}catch(j){}});