document.write('<style type=\"text/css\">');
document.write('<!--');
document.write('td {  font-size: 12px}');
document.write('-->');
document.write('</style>');
document.write('<TABLE cellSpacing=0 cellPadding=0 width=100% bgColor=#eff8ff border=0>');
document.write('<TBODY>');
document.write('<TR vAlign=top>');
document.write('<TD>');
document.write('<TABLE height=126 cellSpacing=1 cellPadding=2 width=100% border=0>');
document.write('<TBODY>');
document.write('<TR>');
document.write('<TD width=102 height=40><IMG height=35 src=\"http://www.yesky.com/image20010518/167580.gif\" width=35 align=left><A href=\"http://www.my5757.com/web/mgf.jsp\" target=_blank>玫瑰坊:<BR>浓情蜜意</A></TD>');
document.write('<TD vAlign=top width=80 rowSpan=3>');
document.write('<DIV align=right><object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0\" width=\"78\" height=\"120\">');
document.write('<param name=movie value=\"http://www.yesky.com/image20010518/173039.swf\">');
document.write('<param name=quality value=high>');
document.write('<embed src=\"http://www.yesky.com/image20010518/173039.swf\" quality=high pluginspage=\"http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application/x-shockwave-flash\" width=\"78\" height=\"120\">');
document.write('</embed>');
document.write('</object>');
document.write('<!--<a href=\"http://www.my5757.com/webwap/zt/50w/index.jsp\" target=_blank><img height=120 src=\"http://www.yesky.com/image20010518/167584.gif\" width=78 border=0></a>-->');
document.write('</DIV>');
document.write('</TD></TR>');
document.write('<TR>');
document.write('<TD width=102 height=40><IMG height=35 src=\"http://www.yesky.com/image20010518/167581.gif\" width=35 align=left><A href=\"http://www.my5757.com/web/aqsj.jsp\" target=_blank>爱情水晶:神奇的测试</A></TD></TR>');
document.write('<TR>');
document.write('<TD width=102 height=40><IMG height=35 src=\"http://www.yesky.com/image20010518/167582.gif\" width=35 align=left><A href=\"http://www.my5757.com/renzc/rzc.jsp\" target=_blank>人之初:健康人生向导</A></TD></TR></TBODY></TABLE>');
document.write('</TD>');
document.write('<TD align=middle>');
document.write('<TABLE height=126 cellSpacing=1 cellPadding=0 bgColor=#a683d8 border=0 width=100%>');
document.write('<TBODY>');
document.write('<TR>');
document.write('<TD vAlign=top bgColor=#ffffff>');
document.write('<TABLE cellSpacing=0 cellPadding=2 width=\"100%\" border=0>');
document.write('<TBODY>');
document.write('<TR>');
document.write('<TD bgColor=#f0eaf8><IMG height=23 src=\"http://www.yesky.com/image20010518/167585.gif\" width=20 align=absMiddle>');
document.write('<A href=\"http://www.my5757.com\" target=_blank><FONT color=#a683d8>短信</FONT></A>&nbsp;');
document.write('<A href=\"http://mms.my5757.com\" target=_blank><FONT color=#a683d8>彩信</FONT></A>');
document.write('<A href=\"http://www.my5757.com/webwap\" target=_blank><FONT color=#a683d8>&nbsp;手机上网</FONT></A>&nbsp;');
document.write('<A href=\"http://www.my5757.com/web/ivr/\" target=_blank><FONT color=#a683d8>语音</FONT></A>');
document.write('</TD>');
document.write('</TR>');
document.write('<TR>');
document.write('<TD>·[<A href=\"http://www.my5757.com/webwap\" target=_blank>WAP</A>]&nbsp;');
document.write('<A href=\"http://www.my5757.com/webwap/itnews.jsp\" target=_blank>天极IT资讯WAP下载</A><BR>');
document.write('·[<A href=\"http://www.my5757.com\" target=_blank>短信</A>]&nbsp;');
document.write('<A href=\"http://www.my5757.com/web/stars.jsp\" target=_blank>手机查询星座运程</A><BR>');
document.write('·[<A href=\"http://mms.my5757.com\" target=_blank>彩信</A>]&nbsp;');
document.write('<A href=\"http://mms.my5757.com/imgbrowse.jsp?cataid=0212\" target=_blank>卡通彩图随意下载</A><BR>');
document.write('·[<A href=\"http://mms.my5757.com\" target=_blank>彩信</A>]&nbsp;');
document.write('<A href=\"http://mms.my5757.com/imgbrowse.jsp?cataid=0103\" target=_blank>体育运动经典彩图</A><BR>');
document.write('·[<A href=\"http://www.my5757.com\" target=_blank>短信</A>]&nbsp;');
document.write('<A href=\"http://www.my5757.com/diange/\" target=_blank>给远方的爱人点歌</A></TD>');
document.write('</TR></TBODY></TABLE></TD></TR></TBODY></TABLE>');
document.write('</TD>');
document.write('<TD align=middle>');
document.write('<TABLE class=shadow cellSpacing=0 cellPadding=4 width=100% border=0>');
document.write('<TBODY>');
document.write('<TR>');
document.write('<TD bgColor=#eff8ff><A href=\"http://mms.my5757.com/send.jsp?id=animation/yy0018.gif\" target=_blank><IMG height=55 src=\"http://www.yesky.com/image20010518/167589.gif\" width=55 border=0></A></TD>');
document.write('<TD bgColor=#eff8ff><A href=\"http://mms.my5757.com/send.jsp?id=animation/yy0019.gif\" target=_blank><IMG height=55 src=\"http://www.yesky.com/image20010518/167590.gif\" width=55 border=0></A></TD>');
document.write('<TD bgColor=#eff8ff><A href=\"http://mms.my5757.com/send.jsp?id=animation/yy0024.gif\" target=_blank><IMG height=55 src=\"http://www.yesky.com/image20010518/167591.gif\" width=55 border=0></A></TD></TR>');
document.write('<TR>');
document.write('<TD bgColor=#eff8ff><A href=\"http://mms.my5757.com/send.jsp?id=image/gaoxiao005.gif\" target=_blank><IMG height=55 src=\"http://www.yesky.com/image20010518/167592.gif\" width=55 border=0></A></TD>');
document.write('<TD bgColor=#eff8ff><A href=\"http://mms.my5757.com/send.jsp?id=image/06G_026.gif\" target=_blank><IMG height=55 src=\"http://www.yesky.com/image20010518/167593.gif\" width=55 border=0></A></TD>');
document.write('<TD bgColor=#eff8ff><A href=\"http://mms.my5757.com/send.jsp?id=image/20040614027.gif\" target=_blank><IMG height=55 src=\"http://www.yesky.com/image20010518/167594.gif\" width=55 border=0></A></TD></TR></TBODY></TABLE>');
document.write('</TD>');
document.write('<TD align=right>');
document.write('<TABLE height=126 cellSpacing=1 cellPadding=0 width=100% bgColor=#a683d8 border=0>');
document.write('<TBODY>');
document.write('<TR>');
document.write('<TD vAlign=top bgColor=#ffffff>');
document.write('<TABLE cellSpacing=0 cellPadding=2 width=\"100%\" border=0>');
document.write('<TBODY>');
document.write('<TR>');
document.write('<TD bgColor=#f0eaf8><IMG height=23 src=\"http://www.yesky.com/image20010518/167586.gif\" width=32 align=absMiddle>');
document.write('<A href=\"http://mms.my5757.com/ringbrowse.jsp?cataid=03\" target=_blank><FONT color=#a683d8>和弦&nbsp;</FONT></A>');
document.write('<A href=\"http://mms.my5757.com/ringbrowse.jsp?cataid=04\" target=_blank><FONT color=#a683d8>特殊音效</FONT></A>&nbsp;');
document.write('<A href=\"http://www.my5757.com/web/RingListMore.jsp\" target=_blank><FONT color=#a683d8>单音</FONT></A></TD>');
document.write('</TR>');
document.write('<TR>');
document.write('<TD>[<A href=\"http://mms.my5757.com/ringbrowse.jsp?cataid=03\" target=_blank>和弦</A>]&nbsp;');
document.write('<A href=\"http://mms.my5757.com/send.jsp?id=ring/hexuan/public_audio_203091.mid\" target=_blank>东风破</A>');
document.write('<A href=\"http://mms.my5757.com/send.jsp?id=ring/hexuan/24772.mid\" target=_blank>&nbsp;半岛铁盒&nbsp;</A>');
document.write('<A href=\"http://mms.my5757.com/send.jsp?id=ring/hexuan/22369.mid\" target=_blank>十年</A><BR>');
document.write('[<A href=\"http://mms.my5757.com/ringbrowse.jsp?cataid=03\" target=_blank>和弦</A>]');
document.write('<A href=\"http://mms.my5757.com/send.jsp?id=ring/hexuan/j35.wma\" target=_blank>&nbsp;十面埋伏</A>');
document.write('<A href=\"http://mms.my5757.com/send.jsp?id=ring/hexuan/j34.wma\" target=_blank>&nbsp;祝酒歌－刀郎</A><BR>');
document.write('[<A href=\"http://mms.my5757.com/ringbrowse.jsp?cataid=03\" target=_blank>和弦</A>]');
document.write('<A href=\"http://mms.my5757.com/send.jsp?id=ring/hexuan/j21.wma\" target=_blank>&nbsp;向左走向右走</A>');
document.write('<A href=\"http://mms.my5757.com/send.jsp?id=ring/hexuan/j24.wma\" target=_blank>&nbsp;我不是黄蓉</A><BR>');
document.write('[<A href=\"http://mms.my5757.com/ringbrowse.jsp?cataid=04\" target=_blank>音效</A>]');
document.write('<A href=\"http://mms.my5757.com/send.jsp?id=ring/yinxiao/15037.wma\" target=_blank>&nbsp;大话西游经典</A>');
document.write('<A href=\"http://mms.my5757.com/send.jsp?id=ring/yinxiao/rpGl2v.wma\" target=_blank>&nbsp;新闻联播</A><BR>');
document.write('[<A href=\"http://mms.my5757.com/ringbrowse.jsp?cataid=04\" target=_blank>音效</A>]');
document.write('<A href=\"http://mms.my5757.com/send.jsp?id=ring/yinxiao/13637.wma\" target=_blank>&nbsp;老虎</A>');
document.write('<A href=\"http://mms.my5757.com/send.jsp?id=ring/yinxiao/sx031.wma\" target=_blank>&nbsp;烈马</A>');
document.write('<A href=\"http://mms.my5757.com/send.jsp?id=ring/yinxiao/9oDf00.wma\" target=_blank>&nbsp;月夜狼嚎</A>');
document.write('</TD>');
document.write('</TR></TBODY></TABLE></TD></TR></TBODY></TABLE>');
document.write('</TD>');
document.write('</TR></TBODY></TABLE>');
