#if !defined(AFX_TESTACTIVE2IE_H__4AC13705_F76F_4FAF_A629_9EB1809D5F0F__INCLUDED_)
#define AFX_TESTACTIVE2IE_H__4AC13705_F76F_4FAF_A629_9EB1809D5F0F__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTestActive2IE wrapper class

class CTestActive2IE : public CWnd
{
protected:
	DECLARE_DYNCREATE(CTestActive2IE)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xf6daf276, 0xf62f, 0x4322, { 0x86, 0x4d, 0x18, 0x7d, 0x3e, 0x39, 0x75, 0x51 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	BOOL SetIP(LPCTSTR IP, LPCTSTR Mak, LPCTSTR GatWay, LPCTSTR DNS1, LPCTSTR DNS2);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TESTACTIVE2IE_H__4AC13705_F76F_4FAF_A629_9EB1809D5F0F__INCLUDED_)
