// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "testactive2ie.h"

/////////////////////////////////////////////////////////////////////////////
// CTestActive2IE

IMPLEMENT_DYNCREATE(CTestActive2IE, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CTestActive2IE properties

/////////////////////////////////////////////////////////////////////////////
// CTestActive2IE operations

BOOL CTestActive2IE::SetIP(LPCTSTR IP, LPCTSTR Mak, LPCTSTR GatWay, LPCTSTR DNS1, LPCTSTR DNS2)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		IP, Mak, GatWay, DNS1, DNS2);
	return result;
}

void CTestActive2IE::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
