document.write('');
document.write('');
document.write('');
document.write('');
document.write('<table  border="0" valign=top  cellspacing="1" cellpadding="0" align="center"    valign=middle>');
document.write('  <tr align="left" valign=top>');
document.write('');
document.write('');
document.write('      <td   align="center" valign="middle" >');
document.write('');
document.write('');
document.write('           <TABLE    border="0" cellspacing="1" cellpadding="0"  width=98  height=73   valign=middle  align="center"  bgcolor="#000000" >');
document.write('<TR>');
document.write('	<TD  align="center" valign="middle" bgcolor="#FFFFFF"><a href=" http://pic.yesky.com/pic/128/128088.shtml" target="_blank"  ><img src="http://pic.yesky.com/picupload1/20050830/134902main.jpg"   border="0"   name=MM    width=98  height=73></a>');
document.write('</TD>');
document.write('</TR>');
document.write('</TABLE>');
document.write('<TABLE align="center">');
document.write('<TR  height="40"   valign=top>');
document.write('	<TD  align="center"  valign=top width=98> <a href=" http://pic.yesky.com/pic/128/128088.shtml" target="_blank" ><font color="black">风华绝代的"罪"：世界电影9大名妓</font></a>');
document.write('</TD>');
document.write('</TR>');
document.write('</TABLE>');
document.write('');
document.write('');
document.write('');
document.write('      </td>      ');
document.write('');
document.write('            ');
document.write('      <td   align="center" valign="middle" >');
document.write('');
document.write('');
document.write('           <TABLE    border="0" cellspacing="1" cellpadding="0"  width=98  height=73   valign=middle  align="center"  bgcolor="#000000" >');
document.write('<TR>');
document.write('	<TD  align="center" valign="middle" bgcolor="#FFFFFF"><a href=" http://pic.yesky.com/pic/128/128020.shtml" target="_blank"  ><img src="http://pic.yesky.com/picupload1/20050830/103609main.jpg"   border="0"   name=MM    width=98  height=73></a>');
document.write('</TD>');
document.write('</TR>');
document.write('</TABLE>');
document.write('<TABLE align="center">');
document.write('<TR  height="40"   valign=top>');
document.write('	<TD  align="center"  valign=top width=98> <a href=" http://pic.yesky.com/pic/128/128020.shtml" target="_blank" ><font color="black">2005超级女声冠军李宇春壁纸</font></a>');
document.write('</TD>');
document.write('</TR>');
document.write('</TABLE>');
document.write('');
document.write('');
document.write('');
document.write('      </td>      ');
document.write('');
document.write('            ');
document.write('      <td   align="center" valign="middle" >');
document.write('');
document.write('');
document.write('           <TABLE    border="0" cellspacing="1" cellpadding="0"  width=98  height=73   valign=middle  align="center"  bgcolor="#000000" >');
document.write('<TR>');
document.write('	<TD  align="center" valign="middle" bgcolor="#FFFFFF"><a href=" http://pic.yesky.com/pic/127/127508.shtml" target="_blank"  ><img src="http://pic.yesky.com/picupload1/20050828/234542main.jpg"   border="0"   name=MM    width=98  height=73></a>');
document.write('</TD>');
document.write('</TR>');
document.write('</TABLE>');
document.write('<TABLE align="center">');
document.write('<TR  height="40"   valign=top>');
document.write('	<TD  align="center"  valign=top width=98> <a href=" http://pic.yesky.com/pic/127/127508.shtml" target="_blank" ><font color="black">明星刚出道形象大曝光</font></a>');
document.write('</TD>');
document.write('</TR>');
document.write('</TABLE>');
document.write('');
document.write('');
document.write('');
document.write('      </td>      ');
document.write('</tr><tr>');
document.write('            ');
document.write('      <td   align="center" valign="middle" >');
document.write('');
document.write('');
document.write('           <TABLE    border="0" cellspacing="1" cellpadding="0"  width=98  height=73   valign=middle  align="center"  bgcolor="#000000" >');
document.write('<TR>');
document.write('	<TD  align="center" valign="middle" bgcolor="#FFFFFF"><a href=" http://pic.yesky.com/pic/127/127397.shtml" target="_blank"  ><img src="http://pic.yesky.com/picupload1/20050828/123155main.jpg"   border="0"   name=MM    width=98  height=73></a>');
document.write('</TD>');
document.write('</TR>');
document.write('</TABLE>');
document.write('<TABLE align="center">');
document.write('<TR  height="40"   valign=top>');
document.write('	<TD  align="center"  valign=top width=98> <a href=" http://pic.yesky.com/pic/127/127397.shtml" target="_blank" ><font color="black">回顾李宇春决赛夺冠之路组图</font></a>');
document.write('</TD>');
document.write('</TR>');
document.write('</TABLE>');
document.write('');
document.write('');
document.write('');
document.write('      </td>      ');
document.write('');
document.write('            ');
document.write('      <td   align="center" valign="middle" >');
document.write('');
document.write('');
document.write('           <TABLE    border="0" cellspacing="1" cellpadding="0"  width=98  height=73   valign=middle  align="center"  bgcolor="#000000" >');
document.write('<TR>');
document.write('	<TD  align="center" valign="middle" bgcolor="#FFFFFF"><a href=" http://pic.yesky.com/pic/127/127285.shtml" target="_blank"  ><img src="http://pic.yesky.com/picupload1/20050828/112225main.jpg"   border="0"   name=MM    width=98  height=73></a>');
document.write('</TD>');
document.write('</TR>');
document.write('</TABLE>');
document.write('<TABLE align="center">');
document.write('<TR  height="40"   valign=top>');
document.write('	<TD  align="center"  valign=top width=98> <a href=" http://pic.yesky.com/pic/127/127285.shtml" target="_blank" ><font color="black">2005"超级女声"年度总决赛组图回顾</font></a>');
document.write('</TD>');
document.write('</TR>');
document.write('</TABLE>');
document.write('');
document.write('');
document.write('');
document.write('      </td>      ');
document.write('');
document.write('            ');
document.write('      <td   align="center" valign="middle" >');
document.write('');
document.write('');
document.write('           <TABLE    border="0" cellspacing="1" cellpadding="0"  width=98  height=73   valign=middle  align="center"  bgcolor="#000000" >');
document.write('<TR>');
document.write('	<TD  align="center" valign="middle" bgcolor="#FFFFFF"><a href=" http://pic.yesky.com/pic/127/127268.shtml" target="_blank"  ><img src="http://pic.yesky.com/picupload1/20050828/104907main.jpg"   border="0"   name=MM    width=98  height=73></a>');
document.write('</TD>');
document.write('</TR>');
document.write('</TABLE>');
document.write('<TABLE align="center">');
document.write('<TR  height="40"   valign=top>');
document.write('	<TD  align="center"  valign=top width=98> <a href=" http://pic.yesky.com/pic/127/127268.shtml" target="_blank" ><font color="black">“超级女声”纪念册提前大曝光</font></a>');
document.write('</TD>');
document.write('</TR>');
document.write('</TABLE>');
document.write('');
document.write('');
document.write('');
document.write('      </td>      ');
document.write('</tr><tr>');
document.write('            ');
document.write('  </tr>');
document.write('</table>');
