(function(){var m=Handlebars.template;(Handlebars.discovery=Handlebars.discovery||{}).templates=m(function(g,k,e,i,a){function b(a,d,b){var c="",f;c+='\n        <section id="';(f=e.id)?f=f.call(a,{hash:{},data:d}):(f=a.id,f=typeof f===r?f.apply(a):f);c+=o(f)+'" class="';(f=e.className)?f=f.call(a,{hash:{},data:d}):(f=a.className,f=typeof f===r?f.apply(a):f);c+=o(f)+'">\n            <header class="discovery-col-header">\n\n                ';if((f=e["if"].call(a,d.index===d.length-1,{hash:{},inverse:j.noop,
fn:j.program(3,q,d),data:d}))||f===0)c+=f;c+="\n\n                ";if((f=e["if"].call(a,a.type==="organic",{hash:{},inverse:j.noop,fn:j.programWithDepth(h,d,b),data:d}))||f===0)c+=f;c+="\n                ";if((f=e["if"].call(a,a.type==="promoted",{hash:{},inverse:j.noop,fn:j.program(7,l,d),data:d}))||f===0)c+=f;c+='\n\n            </header>\n            <ul class="discovery-posts">\n            </ul>\n        </section>\n    ';return c}function q(a,d){var f="";f+='\n                    \n                    <div class="discovery-options">\n                        <span class="publisher-anchor-color"><a href="#" class="discovery-help" data-action="discovery-help">'+
o(e.t.call(a,gettext("What's this?"),{hash:{},data:d}))+"</a></span>\n                    </div>\n                ";return f}function h(a,d,f){var c="";c+="\n                    <h2>"+o(e.t.call(a,gettext("Also on %(forumName)s"),{hash:{forumName:{partial:"forumName",context:f.forum,executePartial:!0}},data:d}))+"</h2>\n                ";return c}function l(a,d){var f="";f+="\n                    <h2>"+o(e.t.call(a,gettext("Around The Web"),{hash:{},data:d}))+"</h2>\n                ";return f}function d(a,
d,f){var c="",b,h;c+='\n        <li class="discovery-post" id="discovery-link-';(b=e.domIdSuffix)?b=b.call(a,{hash:{},data:d}):(b=a.domIdSuffix,b=typeof b===r?b.apply(a):b);c+=o(b)+'">\n            <header class="discovery-post-header">\n                <h3 title="';(b=e.title)?b=b.call(a,{hash:{},data:d}):(b=a.title,b=typeof b===r?b.apply(a):b);c+=o(b)+'">\n                    <a ';if((b=j.invokePartial(i.linkAttributes,"linkAttributes",a,e,i,d))||b===0)c+=b;c+=' data-role="discovery-thread-title" class="title publisher-anchor-color line-truncate" data-line-truncate="2">\n                        '+
o(e.html.call(a,a.title,{hash:{},data:d}))+"\n                    </a>\n\n                    ";if((h=e["if"].call(a,(b=f.variant,b==null||b===!1?b:b.inlineMeta),{hash:{},inverse:j.noop,fn:j.program(17,u,d),data:d}))||h===0)c+=h;c+="\n\n                </h3>\n\n                ";if((h=e.unless.call(a,(b=f.variant,b==null||b===!1?b:b.inlineMeta),{hash:{},inverse:j.noop,fn:j.program(25,s,d),data:d}))||h===0)c+=h;c+="\n\n            </header>\n\n            ";if((h=e["if"].call(a,(b=f.variant,b==null||
b===!1?b:b.contentPreviews)&&a.preview,{hash:{},inverse:j.noop,fn:j.program(30,w,d),data:d}))||h===0)c+=h;c+="\n\n        </li>\n    ";return c}function u(a,d){var b="",c;b+="\n                        ";if((c=e["if"].call(a,a.posts>0,{hash:{},inverse:j.program(20,t,d),fn:j.program(18,f,d),data:d}))||c===0)b+=c;b+="\n                        ";if((c=e["if"].call(a,a.brand,{hash:{},inverse:j.noop,fn:j.program(23,n,d),data:d}))||c===0)b+=c;b+="\n                    ";return b}function f(a,d){var b="",
c;b+='\n                            <span class="inline-meta">\n                                ';if((c=j.invokePartial(i.discoveryPostCount,"discoveryPostCount",a,e,i,d))||c===0)b+=c;b+="\n                            </span>\n                        ";return b}function t(a,b){var d="",c;d+="\n                            ";if((c=e["if"].call(a,a.createdAgo,{hash:{},inverse:j.noop,fn:j.program(21,x,b),data:b}))||c===0)d+=c;d+="\n                        ";return d}function x(a,b){var d="",c;d+='\n                                <span class="inline-meta">';
(c=e.createdAgo)?c=c.call(a,{hash:{},data:b}):(c=a.createdAgo,c=typeof c===r?c.apply(a):c);d+=o(c)+"</span>\n                            ";return d}function n(a,d){var b="",c;b+='\n                            <span class="inline-meta">\n                                ';(c=e.brand)?c=c.call(a,{hash:{},data:d}):(c=a.brand,c=typeof c===r?c.apply(a):c);b+=o(c)+"\n                            </span>\n                        ";return b}function s(a,b){var d="",c;d+='\n                    <ul class="meta">\n                        ';
if((c=e["if"].call(a,a.posts>0,{hash:{},inverse:j.noop,fn:j.program(26,y,b),data:b}))||c===0)d+=c;d+="\n                        ";if((c=e["if"].call(a,a.createdAgo,{hash:{},inverse:j.noop,fn:j.program(28,m,b),data:b}))||c===0)d+=c;d+="\n                    </ul>\n                ";return d}function y(a,d){var b="",c;b+='\n                            <li class="comments">\n                                ';if((c=j.invokePartial(i.discoveryPostCount,"discoveryPostCount",a,e,i,d))||c===0)b+=c;b+="\n                            </li>\n                        ";
return b}function m(a,b){var d="",c;d+='\n                            <li class="time">';(c=e.createdAgo)?c=c.call(a,{hash:{},data:b}):(c=a.createdAgo,c=typeof c===r?c.apply(a):c);d+=o(c)+"</li>\n                        ";return d}function w(a,d){var b="",c;b+="\n                ";if((c=j.invokePartial(i.discoveryContentPreview,"discoveryContentPreview",a,e,i,d))||c===0)b+=c;b+="\n            ";return b}function z(){return'target="_blank" rel="nofollow"'}function A(a,b){var d="";d+="\n        "+o(e.t.call(a,
gettext("1 comment"),{hash:{},data:b}))+"\n    ";return d}function B(a,b){var d="";d+="\n        "+o(e.t.call(a,gettext("%(numPosts)s comments"),{hash:{numPosts:a.posts},data:b}))+"\n    ";return d}this.compilerInfo=[2,">= 1.0.0-rc.3"];var e=e||g.helpers,i=i||g.partials,a=a||{},g="",p,o=this.escapeExpression,r="function",j=this;if((p=e.partial.call(k,"discoveryMain",{hash:{},inverse:j.noop,fn:j.programWithDepth(function(a,d,f){var c="",h;c+='\n<div id="';(h=e.id)?h=h.call(a,{hash:{},data:d}):(h=a.id,
h=typeof h===r?h.apply(a):h);c+=o(h)+'" class="discovery-main">\n    <div id="discovery-note" style="display:none;">\n        <div class="alert">\n        <a href="#" class="close" data-action="discovery-help-close" title="'+o(e.t.call(a,gettext("Close this box"),{hash:{},data:d}))+'">\u00d7</a>\n        '+o(e.t.call(a,gettext("Disqus helps you find new and interesting content, discussions and products. Some sponsors and ecommerce sites may pay us for these recommendations and links. %(learnMore)s or %(feedback)s."),
{hash:{learnMore:{partial:"learnMore",context:f,executePartial:!0},feedback:{partial:"feedback",context:f,executePartial:!0}},data:d}))+"\n        </div>\n    </div>\n\n    ";if((h=e.each.call(a,a.sections,{hash:{},inverse:j.noop,fn:j.programWithDepth(b,d,a),data:d}))||h===0)c+=h;c+="\n\n</div>\n";return c},a,k),data:a}))||p===0)g+=p;g+="\n\n";if((p=e.partial.call(k,"learnMore",{hash:{},inverse:j.noop,fn:j.program(9,function(a,d){var b="";b+='\n    <a href="http://help.disqus.com/customer/portal/articles/666278-introducing-promoted-discovery-and-f-a-q-"\n        target="_blank">'+
o(e.t.call(a,gettext("Learn more"),{hash:{},data:d}))+"</a>\n";return b},a),data:a}))||p===0)g+=p;g+="\n\n";if((p=e.partial.call(k,"feedback",{hash:{},inverse:j.noop,fn:j.program(11,function(a,d){var b="";b+='\n    <a href="https://www.surveymonkey.com/s/GHK872T" target="_blank">\n        '+o(e.t.call(a,gettext("give us feedback"),{hash:{},data:d}))+"</a>\n";return b},a),data:a}))||p===0)g+=p;g+="\n\n";if((p=e.partial.call(k,"forumName",{hash:{},inverse:j.noop,fn:j.program(13,function(a,d){var b=
"",c;b+="\n    <strong>";(c=e.name)?c=c.call(a,{hash:{},data:d}):(c=a.name,c=typeof c===r?c.apply(a):c);b+=o(c)+"</strong>\n";return b},a),data:a}))||p===0)g+=p;g+="\n\n";if((p=e.partial.call(k,"discoveryCollection",{hash:{},inverse:j.noop,fn:j.program(15,function(a,b){var f="",c;f+="\n    ";if((c=e.each.call(a,a.collection,{hash:{},inverse:j.noop,fn:j.programWithDepth(d,b,a),data:b}))||c===0)f+=c;f+="\n";return f},a),data:a}))||p===0)g+=p;g+="\n\n";if((p=e.partial.call(k,"linkAttributes",{hash:{},
inverse:j.noop,fn:j.program(32,function(a,b){var d="",c;d+='\n    href="';(c=e.redirectUrl)?c=c.call(a,{hash:{},data:b}):(c=a.redirectUrl,c=typeof c===r?c.apply(a):c);d+=o(c)+'" ';if((c=e["if"].call(a,a.brand,{hash:{},inverse:j.noop,fn:j.program(33,z,b),data:b}))||c===0)d+=c;d+="\n";return d},a),data:a}))||p===0)g+=p;g+="\n\n";if((p=e.partial.call(k,"discoveryContentPreview",{hash:{},inverse:j.noop,fn:j.program(35,function(a,d){var D;var C;var v;var b="",c;b+="\n    <a ";if((c=j.invokePartial(i.linkAttributes,
"linkAttributes",a,e,i,d))||c===0)b+=c;b+=' class="top-comment" data-role="discovery-top-comment">\n        <img src="'+o((C=(v=(c=(c=a.preview,c==null||c===!1?c:c.author),c==null||c===!1?c:c.avatar),c=v,c==null||c===!1?c:c.cache),c=C,typeof c===r?c.apply(a):c))+'" alt="'+o(e.t.call(a,gettext("Avatar"),{hash:{},data:d}))+'" data-role="discovery-avatar">\n        <p><span class="user" data-role="discovery-top-comment-author">'+o((D=(c=(c=a.preview,c==null||c===!1?c:c.author),c==null||c===!1?c:c.name),
c=D,typeof c===r?c.apply(a):c))+'</span> &#8212; <span data-role="discovery-top-comment-snippet" class="line-truncate" data-line-truncate="3">'+o((c=(c=a.preview,c==null||c===!1?c:c.plaintext),typeof c===r?c.apply(a):c))+"</span></p>\n    </a>\n";return b},a),data:a}))||p===0)g+=p;g+="\n\n";if((p=e.partial.call(k,"discoveryPostCount",{hash:{},inverse:j.noop,fn:j.program(37,function(a,b){var d="",c;d+="\n    ";if((c=e["if"].call(a,a.posts===1,{hash:{},inverse:j.program(40,B,b),fn:j.program(38,A,b),
data:b}))||c===0)d+=c;d+="\n";return d},a),data:a}))||p===0)g+=p;g+="\n";return g})})();
DISQUS.define("discovery.collections",function(){var m=DISQUS.JSON,g=_.strip,k=DISQUS.use("discovery.helpers"),e=DISQUS.use("discovery.models"),i=Backbone.Collection.extend({url:function(a){return DISQUS.api.getURL(a)},fetch:function(a){a=a||{};a.reset=!0;return Backbone.Collection.prototype.fetch.call(this,a)},parse:function(a){return a.response}}),a=function(a){var b=a.prototype;return a.extend({url:function(){return b.url.call(this,"discovery/listTopPost.json")},parse:function(a){for(var a=b.parse.call(this,
a),d=0,h=a.length;d<h;d++)a[d].plaintext=g(a[d].message);return a}})}(i),b=function(a){var b=a.prototype;return a.extend({initialize:function(a,b){this.model=e[this.modelName];this.sourceThread=b.sourceThread;this.modelAttributes=b.modelAttributes;this.getBanditJSON=_.memoize(this.getBanditJSON)},parse:function(a){a=b.parse.call(this,a);if("bandit"in a)this.bandit=a.bandit,a=a.results;if(!_.isArray(a))return[];_.each(a,function(a){_.extend(a,this.modelAttributes)},this);return a},getBanditJSON:function(){return m.stringify(this.bandit)}})}(i),
q=function(a){var b=a.prototype;return a.extend({modelName:"RelatedThread",url:function(){return b.url.call(this,"discovery/listRelated.json")},parse:function(a){return this.rejectInvalid(b.parse.call(this,a))},rejectInvalid:function(a){var b=this.sourceThread;if(DISQUS.debug)return a.slice();return _.filter(a,function(a){if(a.id==b.id||a.link==b.link)return this.reportInvalid(a,"Link or id of related thread points back to thread on this page (circular reference)"),!1;if(a.title.search(/^https?:\/\//)===
0)return this.reportInvalid(a,"Title looks like a url (begins with http:// or https://)"),!1;return!0},this)},reportInvalid:function(a,b){var d=k.log;d("An organic link failed validation:",a.title,a.link,"(id =",a.id+")");d("Reason:",b)}})}(b),h=function(a){var b=a.prototype;return a.extend({modelName:"Advertisement",url:function(){return b.url.call(this,"discovery/listPromoted.json")}})}(b),l=function(a){var b=a.prototype;return a.extend({modelName:"TempestAdvertisement",url:"//tempest.services.disqus.com/listPromoted",
fetch:function(a){a=a||{};a.dataType="jsonp";a.data=a.data||{};if(_.has(a.data,"limit"))a.data.count=a.data.limit,delete a.data.limit;_.has(a.data,"thread")&&delete a.data.thread;return b.fetch.call(this,a)}})}(h),a={PostCollection:a,RelatedThreadCollection:q,AdvertisementCollection:h,TempestAdvertisementCollection:l};if(DISQUS.testing)a.BaseCollection=i,a.BaseContentCollection=b;return a});
DISQUS.define("discovery.helpers",function(m,g){var k=!1,e=!1,i=function(){};m.console&&(i=function(){if(e){var a=_.toArray(arguments);a.unshift("[Discovery]");m.console.log.apply?m.console.log.apply(m.console,a):m.console.log(a.join(" "))}});return{config:function(a){k=!!a.lineTruncationEnabled;e=!!a.consoleLoggingEnabled},isMobile:function(){return DISQUS.browser.mobile},log:i,allowLog:function(a){if(a===g)return e;e=!!a},allowLineTruncate:function(a){if(a===g)return k;k=!!a},lineTruncate:function(a,
b){function q(){return e.scrollHeight-e.offsetHeight>0.2*f}function h(){d.lastChild&&!_.contains(["...","\u2026"],d.lastChild.nodeValue)&&(g=d.appendChild(m.document.createTextNode(" "+t)),q()&&(d.removeChild(g),d.removeChild(d.lastChild),h()))}if(k){var l=DISQUS.logError||function(){};if(!a.closest("body").length)return void l("lineTruncate called on el not on DOM");if(a.text().length<1)return void l("lineTruncated called on empty el");if(_.any(a.children(),function(a){return a.nodeType!==3}))return void l("lineTruncate called on non-flat el");
var d=a[0],e=d;if(a.css("display")!=="block")for(;e.parentNode;)if(e=e.parentNode,$(e).css("display")==="block")break;var f=parseFloat(a.css("font-size"),10);if(q()){var b=b||{},l=b.lines||1,t=b.ellipsis,g,n=a.text();if(n.length){var s=a.width()/f,l=parseInt(s*l,10),n=n.split(/\s/),s=0;a.empty();for(var i=0,v=n.length;i<v;i++){s+=n[i].length+1;if(s>=l)break;d.appendChild(document.createTextNode(" "+n[i]))}if(q()){do g=d.removeChild(d.lastChild);while(q())}else{do g=d.appendChild(document.createTextNode(" "+
n[i++]));while(!q()&&i<v);d.removeChild(g)}t&&(_.isString(t)||(t="\u2026"),h())}}}},balancedPartition:function(a){var b=_.keys(a),q=Math.floor(_.reduce(a,function(a,b){return a+b},0)/2),h=b.length+1;q+=1;var l=Array(h),d,e;for(d=0;d<h;d++)l[d]=Array(q),l[d][0]={};for(e=1;e<q;e++)l[0][e]=!1;var f,g,i,n={};for(e=1;e<q;e++)for(d=1;d<h;d++){f=b[d-1];g=a[f];i=_.clone(l[d-1][e]);if(!i&&g<=e&&(i=_.clone(l[d-1][e-g])))i[f]=g,n=i;l[d][e]=i}return[n,_.omit(a,_.keys(n))]}}});
DISQUS.define("discovery.models",function(){var m=DISQUS.use("time"),g=function(a){var b=a.prototype;return a.extend({defaults:{redirectUrl:null,signedUrl:null,userId:null,sourceThreadId:null,forumId:null,forum:null,majorVersion:null,variant:null,isExperiment:!1},redirectPayload:function(){var a={url:this.get("signedUrl"),imp:DISQUS.juggler.impId,forum_id:this.get("forumId"),forum:this.get("forum"),thread_id:this.get("sourceThreadId"),major_version:this.get("majorVersion")};if(this.get("isExperiment"))a.variant=
this.get("variant");if(this.has("userId"))a.user_id=this.get("userId");if(this.collection&&this.collection.bandit)a.bandit=this.collection.getBanditJSON();return a},redirectUrl:function(){var a=this.get("redirectUrl"),b=this.redirectPayload();return DISQUS.serialize(a,b)},toJSON:function(){var a=b.toJSON.call(this);a.redirectUrl=this.redirectUrl();return a},toString:function(){return this.get("title")+" "+this.get("link")+" (id = "+this.id+")"}})}(Backbone.Model),k=function(a){var b=a.prototype;return a.extend({defaults:_.defaults({createdAgo:!1},
b.defaults),initialize:function(){if(this.get("createdAgo")){var a=m.assureTzOffset(this.get("createdAt")),a=moment(a,m.ISO_8601);this.set("createdAgo",a.fromNow())}},redirectPayload:function(){var a=b.redirectPayload.call(this);_.extend(a,{thread:this.id,zone:"internal_discovery"});return a},toJSON:function(){var a=b.toJSON.call(this);if(a.preview)a.preview=a.preview.toJSON();return a},toString:function(){return"organic link: "+b.toString.call(this)}})}(g),e=function(a){var b=a.prototype;return a.extend({idAttribute:"body_id",
defaults:_.defaults({brand:null,headline:null,text:null,url:null,advertisement_id:null,body_id:null,mobile:!0},b.defaults),get:function(a){if(a==="title")return this.attributes.headline;if(a==="link")return this.attributes.url;return b.get.call(this,a)},redirectPayload:function(){var a=b.redirectPayload.call(this);_.extend(a,{zone:"promoted_discovery",advertisement_id:this.get("advertisement_id")});if(this.has("body_id"))a.body_id=this.get("body_id");return a},toJSON:function(){var a=b.toJSON.call(this);
a.title=a.headline;a.link=a.url;return a},toString:function(){return"promoted link: "+b.toString.call(this)}})}(g),i=function(a){return a.extend({idAttribute:"advertisement_id",parse:function(a){a.signedUrl=a.signed_url;delete a.signed_url;return a}})}(e),k={RelatedThread:k,Advertisement:e,TempestAdvertisement:i};if(DISQUS.testing)k.BaseContentModel=g;return k});
DISQUS.define("discovery",function(){var m=DISQUS.use("discovery.collections"),g=DISQUS.use("discovery.views"),k=DISQUS.use("discovery.helpers"),e=Backbone.Model.extend({defaults:{name:"promoted",inlineMeta:!0,contentPreviews:!1,promotedEnabled:!0,topPlacementEnabled:!1,isExperiment:!1,redirectUrl:"//redirect.disqus.com/url",listRelatedLimit:null,listPromotedLimit:null,httpTimeout:1E4,sourceThread:null,sourceForum:null,useNewAdserver:!1,help:!1,display:!1,columnEveningEnabled:!0,numColumns:2,minPerColumn:1,
maxPerColumn:4,toleranceCoefficient:1.2,minWidthForColumnLayout:440,containerId:"discovery",topPlacementContainerId:"discovery-top",innerContainerName:"discovery-main",sectionNames:["col-organic","col-promoted"],collectionTagName:"ul",collectionClassName:"discovery-posts",consoleLoggingEnabled:DISQUS.debug,lineTruncationEnabled:!0,session:null,js:null,css:null},initialize:function(){var a=this;a.get("useNewAdserver")&&(a.set("isExperiment",!0),a.set("name","tempest"));a.createDataReferences();a.set("innerContainerId",
a.get("innerContainerName")+"-"+a.cid);a.set("sectionIds",_.map(a.get("sectionNames"),function(b){return b+"-"+a.cid}));var b=a.get("session");a.get("topPlacementEnabled")&&b.isAnonymous()&&a.set("containerId",a.get("topPlacementContainerId"));a.once("change:display",function(){a.onComplete()});_.bindAll(a,"getContentPreviews","validateData","showData");a.run()},commonClickMetadata:function(){var a=this.get("sourceThread"),b=this.get("sourceForum"),a={redirectUrl:this.get("redirectUrl"),sourceThreadId:a.id,
forumId:b.pk,forum:b.id,majorVersion:this.majorVersion(),variant:this.get("name"),isExperiment:this.get("isExperiment")};if((b=this.get("session"))&&b.isRegistered())a.userId=b.user.id;return a},createDataReferences:function(){function a(){this.sourceThread=b.get("sourceThread");this.modelAttributes=b.commonClickMetadata()}var b=this;b.collections=[];var e=new a;e.modelAttributes.createdAgo=!0;this.threads=new m.RelatedThreadCollection(null,e);this.collections.push(this.threads);if(this.get("promotedEnabled"))this.ads=
new (this.get("useNewAdserver")?m.TempestAdvertisementCollection:m.AdvertisementCollection)(null,new a),this.collections.push(this.ads)},run:function(){var a=_.bind(this.onComplete,this);this.getData().then(this.validateData).then(this.showData).otherwise(a)},getData:function(){function a(){this.timeout=b.get("httpTimeout");this.data={thread:b.get("sourceThread").id,limit:e/b.collections.length*b.get("maxPerColumn")}}var b=this,e=b.get("numColumns"),h=new a;if(b.has("listRelatedLimit"))h.data.limit=
b.get("listRelatedLimit");var l=b.listRelatedRequest=when(b.threads.fetch(h));b.get("contentPreviews")&&(l=l.then(b.getContentPreviews));if(!b.get("promotedEnabled"))return l;h=new a;if(b.has("listPromotedLimit"))h.data.limit=b.get("listPromotedLimit");h=b.listPromotedRequest=when(b.ads.fetch(h));return when.join(l,h)},getContentPreviews:function(){var a=this.threads.pluck("id"),b=this.collections.length,e=this.get("numColumns"),h=this.get("minPerColumn");if(a.length<e/b*h)return when.resolve();this.previews=
new m.PostCollection;return(this.listTopPostRequest=when(this.previews.fetch({data:{thread:a},timeout:this.get("httpTimeout")}))).then(_.bind(this.attachPreviews,this))},attachPreviews:function(){var a=this;a.previews.each(function(b){var e=b.get("thread");(e=a.threads.get(e.id||e))&&e.set("preview",b)})},validateCollections:function(){for(var a=this.collections,b=a.length,e=this.get("numColumns"),h=this.get("minPerColumn"),l,d;b>0;)if(d=e/a.length*h,l=a[--b],l.length<d)a.splice(b,1),b=a.length;b=
a.length;if(b>0){e=e/b*this.get("maxPerColumn");for(h=0;h<b;h++)l=a[h],l.length>e&&l.reset(l.slice(0,e))}},validateData:function(){k.isMobile()&&this.ads&&this.ads.length>0&&this.ads.remove(this.ads.where({mobile:!1}));this.validateCollections();if(this.collections.length===0)throw"Not enough data";},showData:function(){function a(a){_.extend(this,a);this.appContext=b.toJSON()}var b=this,e=document.getElementById(b.get("containerId"));if(!e)throw"No container on the DOM";e=b.mainView=new g.MainView(new a({el:e,
model:b}));e.render();var h=b.get("sectionIds"),l=b.get("collectionTagName"),d=b.get("collectionClassName");b.views=_.map(b.collections,function(b,e){return new g.BaseCollectionView(new a({collection:b,el:$("#"+h[e]+" "+l+"."+d)}))});b.views.length===2&&e.$el.find("#"+b.get("innerContainerId")).addClass("doublesection");_.invoke(b.views,"render");if(b.get("columnEveningEnabled")&&e.$el.width()>b.get("minWidthForColumnLayout"))(new g.TwoColumn({views:b.views,fudge:this.get("toleranceCoefficient")})).render();
else{var u=_.min(_.pluck(b.collections,"length"));_.each(b.views,function(a){for(;a.collection.length>u;)a.collection.pop()})}b.set("display",!0)},onComplete:function(a){var b=k.log;if(this.onCompleteCalled)return b("Error: Final reporting function called more than once");this.onCompleteCalled=!0;a&&b("It looks like there was a problem:",a);this.report()},report:function(){var a=k.log,b=this.snapshot(),e=DISQUS.juggler.client("juggler");if(!e)return void a("Cannot report app state, no client found");
a("Sending analytics data about this Discovery impression:");a("init_discovery: ",b);e.emit("init_discovery",b);this.get("darkJester")&&DISQUS.juggler.client("jester",!0).emit("init_discovery",b)},majorVersion:function(){return this.get("promotedEnabled")?"midway":"metadata"},snapshot:function(){var a=this.collections,b=this.threads,b={major_version:this.majorVersion(),internal_organic:b.length,external_organic:0,promoted:0,display:this.get("display"),placement:this.get("containerId")===this.get("topPlacementContainerId")?
"top":"bottom"};if(this.get("promotedEnabled")){var e=this.ads;_.extend(b,{promoted:e.length,promoted_ids:DISQUS.JSON.stringify(e.pluck("advertisement_id"))})}a=_.extend.apply(_,[{}].concat(_.pluck(a,"bandit")));if(!_.isEmpty(a))b.bandit=DISQUS.JSON.stringify(a);if(this.get("isExperiment"))b.variant=this.get("name");return b}}),i={};if(DISQUS.testing)i.DiscoveryApp=e;i.init=function(a){var b=_.object(_.map(["lineTruncationEnabled","consoleLoggingEnabled"],function(b){return b in a?[b,a[b]]:[b,e.prototype.defaults[b]]}));
k.config(b);return new e(a)};return i});
DISQUS.define("discovery.views",function(){var m=DISQUS.use("discovery.helpers"),g=Backbone.View.extend({initialize:function(a){if(a&&a.appContext)this.appContext=a.appContext},getTemplateContext:function(){if(!this.appContext)return{};return{variant:this.appContext}},template:function(a,b){b=b||this.templateName;return DISQUS.renderBlock(b,a)}}),k=function(a){var b=a.prototype;return a.extend({events:{"click [data-redirect]":"handleClick"},handleClick:function(a){this.swapHref(a.currentTarget)},swapHref:function(a){a.setAttribute("data-href",
a.getAttribute("href"));a.setAttribute("href",a.getAttribute("data-redirect"));_.delay(function(){a.setAttribute("href",a.getAttribute("data-href"))},100)},templateName:"discoveryCollection",initialize:function(a){b.initialize.call(this,a);this.elementsSelector="li.discovery-post";this.$elements=this.$el.find(this.elementsSelector);a=this.collection;a.on("remove",this.remove,this);a.on("reset",this.render,this)},truncate:function(){this.$el.find(".line-truncate").each(function(a){a=$(a);m.lineTruncate(a,
{lines:a.attr("data-line-truncate"),ellipsis:!0})})},getTemplateContext:function(){var a=b.getTemplateContext.call(this);a.collection=this.collection.toJSON();var e=this.collection.at(0),h=e.has("id")?"organic-":"promoted-",g=e.idAttribute;_.each(a.collection,function(a){a.domIdSuffix=a[g];a.domIdSuffix=h+a.domIdSuffix});return a},render:function(){this.$el.html(this.template(this.getTemplateContext()));this.$elements=this.$el.find(this.elementsSelector);this.truncate();return this},remove:function(a,
b,e){if(arguments.length===0)return g.prototype.remove.call(this);var h=_.toArray(this.$elements),l=h.splice(e.index,1)[0];$(l).remove();this.$elements=$(h);return this}})}(g),e=function(a,b){this.modelIds=a||[];this.$elements=$(b||[])};_.extend(e.prototype,{height:function(){var a=this;a.heights=[];var b=$(a.$elements),d=b.first().offset().top,d=function(){var a=b.last().offset();return a.top+a.height}()-d,e=0;_.each(b,function(b){b=$(b).height();a.heights.push(b);e+=b});this.interstice=(d-e)/(b.length-
1);return d}});var i=function(){this.divideIntoColumns=function(){var a=this,b=a.subviews[0];a.left=new e;a.right=new e;var d=0;b.collection.each(function(e,f){var g=d++%2===0?"left":"right";a[g].modelIds.push(e.id);Array.prototype.push.call(a[g].$elements,b.$elements[f])})};this.removeOneFromColumn=function(a,b){var d=_.chain(a.modelIds).map(function(b,d){return[b,a.heights[d]]}).sortBy(function(a){return-1*a[1]}).find(function(a){return a[1]<=b}).value()[0],e=this.subviews[0].collection,f=e.models,
g=e.get(d),i=f.indexOf(g),d=[[],[]],n,s=f.length;for(n=0;n<s;n++)d[n%2].push(f[n]);f=d[i%2];f.splice(_.indexOf(f,g),1);f=[];g=(i+1)%2;for(n=0;n<s-1;n++)f.push(d[(n+g)%2].shift());e.reset(f)};this.balanceColumns=function(){var a=this.subviews[0],b=a.collection,d={};b.each(function(b,e){d[e]=a.$elements[e]});var e=m.balancedPartition(d),e=_.sortBy(e,"length"),f=e[0],g=b.models,i=Array(g.length);_.each(e[1],function(a,b){i[2*b]=g[b]});_.each(f,function(a,b){i[2*b+1]=g[b]});b.reset(g)};this.shortenColumn=
function(a,b){this.subviews[0].collection.length%2!==0&&a===this.left?this.removeOneFromColumn(a,this.fudge*b):this.balanceColumns()}},a=function(){this.divideIntoColumns=function(){var a=this.subviews,b=a[0],a=a[1];this.left=new e(b.collection.pluck(b.collection.model.prototype.idAttribute),b.$elements);this.right=new e(a.collection.pluck(a.collection.model.prototype.idAttribute),a.$elements)};this.shortenColumn=function(a,b){for(var d=a===this.left?this.right:this.left,e=b/d.$elements.length,f=
(a===this.left?this.subviews[0]:this.subviews[1]).collection,g=_.chain(a.modelIds).map(function(b,d){return[b,a.heights[d]]}).sortBy(function(a){return a[1]}).value(),i=[],n=0,k=b,k=e;g.length;){var m=g.pop(),q=m[0],m=m[1]+a.interstice;n+m>b&&(d=a);k=Math.abs(b-(n+m));k/=d.$elements.length;k>=e||(e=k,k=a.modelIds.indexOf(q),a.modelIds.splice(k,1),Array.prototype.splice.call(a.$elements,k,1),n+=m,i.push(q))}f.remove(i)}},b=function(b){this.fudge=b.fudge;this.subviews=b.views.slice(0,2);this.subviews.length===
1?i.call(this):a.call(this)};_.extend(b.prototype,{ascendingByHeight:function(){var a=this.left,b=this.right,a=[[a,a.height()],[b,b.height()]];return _.sortBy(a,function(a){return a[1]})},evenColumns:function(a){var b=this.ascendingByHeight(),d=b[0][0],e=b[0][1],f=b[1][0],b=b[1][1];if(e!==b){var e=b-e,g=this.fudge*e,b=_.find(f.heights,function(a){return a+f.interstice<g});if(!a&&b)return this.shortenColumn(f,e),this.divideIntoColumns(),this.evenColumns("do not recurse again");this.increaseMargins(d,
e)}},increaseMargins:function(a,b){var d=b/a.$elements.length;_.each(a.$elements,function(a){var a=$(a),b=parseInt(a.css("margin-bottom"),10)+d;a.css("margin-bottom",b+"px")});(a===this.left?this.right:this.left).$elements.css("clear",a===this.right?"left":"right")},render:function(){this.divideIntoColumns();this.evenColumns();return this}});var q=function(a){var b=a.prototype;return a.extend({templateName:"discoveryMain",events:{"click [data-action=discovery-help]":function(a){a.preventDefault();
this.model.set("help",!0)},"click [data-action=discovery-help-close]":function(a){a.preventDefault();this.model.set("help",!1)}},toggleHelp:function(a){this.$el.find("#discovery-note").toggle();a.trigger("resize")},initialize:function(a){b.initialize.call(this,a);this.model.on("change:display",this.show,this);this.model.on("change:help",this.toggleHelp,this);this.$el.css({position:"absolute",visibility:"hidden",display:"block"})},createSections:function(){var a=this.model,b=DISQUS.discovery.collections,
e=b.RelatedThreadCollection,g=b.AdvertisementCollection,h=a.get("sectionNames"),i=a.get("sectionIds");return _.map(a.collections,function(a,b){var d;a instanceof e?d="organic":a instanceof g&&(d="promoted");return{id:i[b],className:h[b],type:d}})},render:function(){var a=this.model,b=this.createSections();this.$el.html(this.template({id:a.get("innerContainerId"),sections:b,forum:a.get("sourceForum"),session:a.get("session").toJSON()}))},show:function(a){a.get("display")&&(this.$el.css({position:"static",
visibility:"visible"}),a.trigger("resize"))}})}(g);return{BaseCollectionView:k,TwoColumn:b,MainView:q}});