'use strict';window.StackExchange={};function MSIsPlayback(){try{return parent&&parent.WebPlayer}catch(d){return!1}}if(!MSIsPlayback()&&top!=self)throw top.location.replace(document.location),$(function(){$("head").add("body").remove()}),alert("For security reasons, framing is not allowed; click OK to remove the frames."),Error();
StackExchange.init=function(){function d(){$(document).on("click",".convert-to-post",function(a){a.preventDefault();a=$(this).attr("data-confirm");(!a||confirm(a))&&$("<form method='post'/>").attr("action",$(this).attr("href")).appendTo("body").append($("<input type='hidden' name='fkey' />").attr("value",$(this).attr("data-fkey"))).submit()})}function a(){function a(h){StackExchange.options.user.fkey!==h&&(StackExchange.options.user.fkey=h,$("input[name=fkey]").val(h))}function c(){var a=localStorage.getItem(d);
if(!a)return{time:0};a=a.split(/,/);return{fkey:a[0],time:parseInt(a[1],10)}}var d="se:fkey";$(window).on("storage",function(h){h=h.originalEvent;h.key==d&&h.newValue&&a(h.newValue.split(/,/)[0])});try{var h=StackExchange.options.user.fkey,e=c();if(e.fkey!==h)if(StackExchange.options.serverTime>e.time)try{localStorage.setItem(d,h+","+StackExchange.options.serverTime)}catch(j){}else a(e.fkey)}catch(f){}}var c=function(a){if(!window.jQuery)if("complete"!=document.readyState)setTimeout(function(){c(a)},
1E3);else{var d=document.createElement("div");d.id="noscript-padding";var e=document.createElement("div");e.id="noscript-warning";e.innerHTML=a+" requires external JavaScript from another domain, which is blocked or failed to load.";document.body.insertBefore(d,document.body.firstChild);document.body.appendChild(e)}},f=function(){var a=function(a){a?$(a).trigger("popupClose").fadeOutAndRemove():($("#lightbox:not(.no-esc-remove), .message-dismissable, .popup:not(.no-auto-close), .share-tip, .esc-remove").fadeOutAndRemove(),
$(".esc-hide").fadeOut(),window.genuwine&&genuwine.isVisible()&&genuwine.click(),window.profileLink&&profileLink.hide(),StackExchange.topbar&&StackExchange.topbar.hideAll(),$("#lightbox:not(.no-esc-remove), .message-dismissable, .popup:not(.no-auto-close), .share-tip, .esc-remove, .esc-hide").trigger("popupClose",{closeTrigger:"esc"}))};$(document).keyup(function(c){27==c.which&&a()});$("body").mousedown(function(a){var c=$(a.target);if(!c.closest(".ac_results, .popup").length){if(!c.closest(".popup").length){if(1!=
a.which)return;$(".popup:not(.no-auto-close), #lightbox").fadeOutAndRemove().trigger("popupClose",{closeTrigger:"click outside"})}c.closest(".share-tip").length||$(".share-tip").fadeOutAndRemove().trigger("popupClose",{closeTrigger:"click outside"});c.closest(".wmd-prompt-dialog").length||$(".wmd-prompt-dialog, .wmd-prompt-background").fadeOutAndRemove().trigger("popupClose",{closeTrigger:"click outside"})}});$(document).bind("closePopups",function(c){a(c.selectorToClose)})},e=function(){var a=$("#hlinks"),
c=$("#search input[name=q]"),d=c.width(),h=2.5*d,e,j=function(a){c.queue("expand",a)},f=!1,q=!("placeholder"in document.createElement("input"));q&&!StackExchange.options.isMobile&&(""==c[0].value&&(c[0].value="search"),c.bind({focus:function(){"search"==this.value&&(this.value="")}}));c.keydown(function(d){if(f||46>d.keyCode&&8!=d.keyCode&&32!=d.keyCode)return!0;f=!0;clearTimeout(e);c.clearQueue("expand");j(function(h){c[0].placeholder="";a.fadeOut(100,h)});j(function(a){c.animate({width:h,"max-width":h},
100,a)});j(function(){0==c.parent().find(".search-prompt").length&&c.before('<span class="search-prompt">search:</span>')});3==c.queue("expand").length&&c.dequeue("expand")}).focusout(function(){e=setTimeout(function(){j(function(a){c.parent().find(".search-prompt").remove();a()});j(function(a){c.animate({width:d,"max-width":d},100,a)});j(function(h){q&&""==c[0].value&&(c[0].value="search");c[0].placeholder="search";a.fadeIn(100,h)});3==c.queue("expand").length&&c.dequeue("expand");f=!1},200)});$("#search").keydown(function(a){if(13==
a.which&&a.ctrlKey&&c.val())return window.open("/search?q="+encodeURIComponent(c.val()),"_newtab"),!1}).find("input[name=q]").keyup(function(a){27==a.which&&$(this).blur()})};return function(g){StackExchange.options=g;g.serverTimeOffsetSec=g.serverTime-(new Date).getTime()/1E3;c(g.site.name);$.ajaxSetup({cache:!1});StackExchange.init.createJqueryExtensions();g.enableLogging=g.user.isEmployee&&"undefined"!==typeof console&&"undefined"!==typeof console.log;$(function(){f();e();a();d();StackExchange.using(StackExchange.options.user.isAnonymous?
"anonymous":"loggedIn",function(){StackExchange.initialized.resolve()},!0,g.fullPostfix);var c=StackExchange.options.styleCodeAdditionalLang;c&&StackExchange.ifUsing("prettify",function(){return StackExchange.loadJsFile("third-party/prettify/additional-langs/"+c)});StackExchange.ready(function(){genuwine.init(g.user.accountId||null,g.user.inboxUnviewedCount,g.user.notificationsUnviewedCount);g.user.messages&&StackExchange.notify.showMessages(g.user.messages,g.isMobile);g.site.globalAuthDisabled||
(!g.site.isChildMeta&&g.user.isAnonymous&&gauth.checkStackAuth(g.stackAuthUrl),gauth.informStackAuth(g.stackAuthUrl));g.user.isAnonymous||profileLink.init(g.user.gravatar,g.isMobile,g.user.profileUrl+"?tab=activity",g.serverTimeOffsetSec);g.enableUserHovercards&&StackExchange.usermenu.init();StackExchange.tagPreferences?StackExchange.tagPreferences.init():StackExchange.tagmenu.init();$("*[data-tracker]").track()})})}}();
StackExchange.debug={log:function(){},init:function(){this.log=function(d){$(function(){var a=$("#debug-messages");a.length||(a=$("<div id='debug-messages' style='text-align:left;position:fixed;top:50px;left:50px;z-index:1000;background:white;border:2px solid black;width:300px;padding:10px;' />").append($("<span style='cursor:pointer;color:#999'>(close debug messages)</span>").click(function(){$("#debug-messages").remove()})).appendTo("body"));$("<div style='margin-top:10px' />").text(d).appendTo(a)})}}};
StackExchange.initialized=$.Deferred();StackExchange.ready=function(d){StackExchange.initialized.done(d)};if(window.serq)for(var i=0;i<window.serq.length;i++)StackExchange.ready(window.serq[i]);
(function(){var d={anonymous:"full-anon.js",loggedIn:"full.js",prettify:"prettify-full.js",pseudoModerator:"moderator.js",inlineEditing:"full.js",editor:"wmd.js",autocomplete:"third-party/jquery.autocomplete.min.js",tagAutocomplete:"tageditor.js",tagEditor:"tageditornew.js",tagSuggestions:"tagsuggestions.js",mobile:"mobile.js",help:"help.js",inlineTagEditing:"inline-tag-editing.js",mathjaxEditing:"mathjax-editing.js",revisions:"revisions.js",mockups:"external-editor.js",schematics:"external-editor.js",
review:"review.js",translation:"full.js",gps:"full-anon.js",postValidation:"post-validation.js",exploreQuestions:"explore-qlist.js",eventCharts:"events.js",virtualKeyboard:"virtual-keyboard.js"},a={},c={},f,e={},g=function(a,c){return function(h){var d=a[h];d||(d=a[h]=c(h));return d}},l=function(c){var c=a[c],h,d=$.Deferred(),j=$.when(d),e;if(c)for(h=0;h<c.length;h++)(e=c[h].call(null))&&$.isFunction(e.promise)&&(j=$.when(j,e));d.resolve();return j},k=function(){if(!f){var a=$("script[src]").filter(function(){return/stub.*\.js/.test($(this).attr("src"))}).first();
0==a.length?(StackExchange.debug.log("couldn't figure out location of stub.js"),f="/content/js/"):f=a.attr("src").replace(/\/stub.*\.js.*$/,"/")}return f},h=function(a){a&&StackExchange.options.locale&&-1==a.indexOf("third-party")&&(a=a.replace(/^(.*)(.js)(\?.*)?$/,"$1."+StackExchange.options.locale+"$2$3"));return a},n=function(a){var c=$.Deferred(),d=document.createElement("script");d.async="async";d.type="text/javascript";d.src=h(a);d.onload=d.onreadystatechange=function(a,h){if(!d.readyState||
/loaded|complete/.test(d.readyState))h?c.reject():c.resolve()};d.onerror=function(){c.reject()};$("head")[0].appendChild(d);return c.promise()},j=function(a){a=d[a];return!a?$.Deferred().reject().promise():v(a)},v=g({},function(a){var c=k()+a;var a=h(a),d=e["js/"+a];d?a="?v="+d:(StackExchange.debug.log("no cache breaker for "+a),a="");return n(c+a)}),q=g({},function(a){function c(){(d=StackExchange[a])?l(a).done(function(){h.resolve()}):0<e?(e--,StackExchange.debug.log("retrying "+a),setTimeout(c,
20)):(StackExchange.debug.log("object "+a+" not available although file was loaded"),h.reject())}var h=$.Deferred(),d=StackExchange[a],e=3;d?h.resolve():j(a).done(c).fail(h.reject);return h.promise()}),t=$.Deferred(),u=function(a,c,h,j){if(!h&&!t.isResolved())t.done(function(){u(a,c)});else{if(h)for(var e in d)d.hasOwnProperty(e)&&(d[e]=d[e].replace(/^(full(?:-anon)?).js$/,"$1"+(j||"")+".js"));j=q(a);h?t.resolve():j=$.when(j,StackExchange.initialized);j.done(function(){c()}).fail(function(){StackExchange.debug.log("failed to provide object "+
a)});return j}};u.setCacheBreakers=function(a){for(var c in a)a.hasOwnProperty(c)&&(e[c]=a[c])};StackExchange.using=u;StackExchange.ifUsing=function(h,d,j){if("undefined"!==typeof j){if(c["u_"+j])return;c["u_"+j]=!0}StackExchange[h]?d():((j=a[h])||(j=a[h]=[]),j.push(d))};StackExchange.loadJsFile=function(a){return n(k()+a)}})();
String.prototype.formatUnicorn=function(){var d=this.toString();if(!arguments.length)return d;var a=typeof arguments[0],a="string"==a||"number"==a?Array.prototype.slice.call(arguments):arguments[0],c;for(c in a)d=d.replace(RegExp("\\{"+c+"\\}","gi"),a[c]);return d};String.prototype.truncate=function(d,a){var c=this.toString();d&&c.length>d&&(c=c.substr(0,d)+a);return c};String.prototype.splitOnLast=function(d){d=this.lastIndexOf(d);return 0>d?[this]:[this.substr(0,d),this.substr(d)]};
String.prototype.contains=function(d){return-1<this.indexOf(d)};
StackExchange.init.createJqueryExtensions=function(){var d=StackExchange.helpers;$.extend($.expr[":"],{working:function(a){a=$(a).data("working");return"undefined"!==typeof a&&a},data:function(a,c,d){c=d[3];a=$(a).data(c);switch(typeof a){case "undefined":return!1;case "boolean":return a;case "object":return null!==a}return!0},containsCI:function(a,c,d){return 0<=jQuery(a).text().toUpperCase().indexOf(d[3].toUpperCase())}});$.fn.extend({working:function(a){return this.each(function(){$(this).data("working",a)})},
track:function(){return this.each(function(){var a=$(this),c=a.is("a[href]")?a:a.find("a[href]"),d=a.data("tracker");c.each(function(){var a=this.href.splitOnLast("#"),c=a[0];this.href=c+=(c.contains("?")?"&":"?")+d+(a[1]||"")})})},fadeOutAndRemove:function(){return this.each(function(){var a=$(this);a.fadeOut("fast",function(){a.trigger("removing").remove()})})},charCounter:function(a){return this.each(function(){var c=a.target?$(a.target):$(this).parents("form").find("span.text-counter"),f=this;
$(this).bind("blur focus keyup paste charCounterUpdate",d.DelayedReaction(function(){var d=a.min,g=a.max,l=a.setIsValid||function(){},k=f.value?f.value.replace(/\r\n/g,"\n").length:0,h=k>0.8*g?"supernova":k>0.6*g?"hot":k>0.4*g?"warm":"cool",n="";0==k?0==d?(n=function(a){return 1==a.max?"enter up to "+a.max+" charcter":"enter up to "+a.max+" charcters"}({max:g}),l(!0)):(n=function(a){return 1==a.min?"enter at least "+a.min+" character":"enter at least "+a.min+" characters"}({min:d}),l(!1)):k<d?(n=
d-k+" more to go...",l(!1)):(d=g-k,n=0<=d?function(a){return 1==a.count?a.count+" character left":a.count+" characters left"}({count:d}):function(a){return 1==a.count?"too long by "+a.count+" character":"too long by "+a.count+" characters"}({count:Math.abs(d)}),l(k<=g));c.text(n);c.hasClass(h)||c.removeClass("supernova hot warm cool").addClass(h)},100,{sliding:!0}).trigger)})},selectRange:function(a,c){return this.each(function(){if(this.setSelectionRange)this.focus(),this.setSelectionRange(a,c);
else if(this.createTextRange){var d=this.createTextRange();d.collapse(!0);d.moveEnd("character",c);d.moveStart("character",a);d.select()}})},addSpinner:function(a){return this.each(function(){d.addSpinner(this,a)})},addSpinnerAfter:function(a){return this.each(function(){$(this).after(d.getSpinnerImg(a))})},addSpinnerBefore:function(a){return this.each(function(){$(this).before(d.getSpinnerImg(a))})},removeSpinner:function(){return this.each(function(){$(this).find("img.ajax-loader").remove()})},
showErrorMessage:function(a,c){return this.each(function(){d.showErrorMessage(this,a,c)})},showErrorPopup:function(a,c){return this.each(function(){d.showErrorMessage(this,a,c)})},showInfoMessage:function(a,c){return this.each(function(){d.showInfoMessage(this,a,c)})},center:function(a){var a=a||{},c=this.parent();"static"===c.css("position")&&(c=c.offsetParent());var c=c.offset(),d=$(window),a=a.top||Math.max((d.height()-this.outerHeight())/2+d.scrollTop()-c.top+(a.dy||0),0);this.css("position",
"absolute");this.css("top",a+"px");this.css("left",Math.max(20,(d.width()-this.outerWidth())/2+d.scrollLeft()-c.left)+"px");a="calc(50% - "+this.outerWidth()/2+"px)";this.css("left",a);this.css("left","-webkit-"+a);return this},helpOverlay:function(){d.bindHelpOverlayEvents(this);return this},hideHelpOverlay:function(){d.hideHelpOverlay(this);return this},enable:function(){0==arguments.length||arguments[0]?this.removeAttr("disabled").css("cursor","pointer").removeClass("disabled-button"):this.attr("disabled",
"disabled").css("cursor","default").addClass("disabled-button");return this},disable:function(){return this.enable(!1)},loadPopup:function(a){var c=this;c.addSpinnerAfter({padding:"0 3px"});$.ajax({type:"GET",url:a.url,dataType:"html",success:function(d){var e=$(d).elementNodesOnly();e.find(".popup-actions-cancel, .popup-close a").click(function(){StackExchange.helpers.closePopups(".popup");a.lightbox&&$("#lightbox").fadeOutAndRemove()});e.find("input:radio[disabled=disabled] + label.action-label").addClass("action-disabled");
a.hideDescriptions&&e.find("ul.action-list > li:not(.action-selected) .action-desc").hide();d=e.find("input:radio:not(.action-subform input)");d.closest("li").bind("hide-action",function(){var c=$(this),d=".action-subform"+(a.hideDescriptions?", .action-desc":"");c.removeClass("action-selected").find(d).slideUp("fast")}).bind("show-action",function(){var c=$(this);c.hasClass("action-selected")||(c.siblings(".action-selected").trigger("hide-action"),c.addClass("action-selected").find(".action-subform").slideDown("fast",
function(){a.subformShow&&a.subformShow($(this));if(a.subformFocusInput){var c=$(this).find("input[type=text], textarea").not(".actual-edit-overlay").eq(0);c.length&&c.focus()}}),a.hideDescriptions&&c.find(".action-desc").slideDown("fast"),a.actionSelected&&a.actionSelected(c),e.find(".popup-submit").enable())});d.click(function(){$(this).closest("li").trigger("show-action")});e.appendTo(c.parent());a.loaded&&a.loaded(e);d=function(){};if(a.subformShow){var g=e.find("li.action-selected .action-subform");
0<g.length&&(d=function(){g.each(function(){a.subformShow($(this))})})}if(a.lightbox){var l=$('<div id="lightbox"/>').appendTo($("body")).css("height",$(document).height()).fadeIn("fast");e.css("z-index",l.css("z-index")+1)}a.dontCenter||e.center().fadeIn("fast",d)},error:function(a){var d=a.responseText||"Unable to load popup - please try again";c.parent().showErrorMessage(d,{"transient":409==a.status})},complete:d.removeSpinner});return c},asyncLoad:function(a){a=$.extend({callback:null,cache:{}},
a);return this.each(function(){var c=$(this),d=c.find(".async-load");c.is(".async-load")&&(d=d.add(c));d.each(function(){var c=$(this),d=c.data("load-url")||"";if(d&&!c.is(":working")){c.working(!0).addSpinner();var f=function(d){c.html(d).removeClass("async-load").mathjax();if((d=c.data("after-load")||"")||a.callback){for(var d=d.split("."),n,j=0;j<d.length;j++)n=(n||window)[d[j]];n=n||a.callback;"function"===typeof n&&n(c)}},k=a.cache[d];k?window.setTimeout(function(){f(k)},0):$.ajax({type:"GET",
url:d,dataType:"html"}).done(function(c){a.cache[d]=c;f(c)}).fail(function(){c.removeSpinner().showErrorMessage("An error has occurred; please try again")})}})})},mathjax:function(){return this.each(function(){"undefined"!=typeof MathJax&&MathJax.Hub.Typeset(this)})},elementNodesOnly:function(){return this.filter(function(){return 1===this.nodeType})},outerHTML:function(){return $("<div>").append(this.eq(0).clone()).html()}})};
StackExchange.helpers=function(){function d(a,c,d){for(var e=0;e<d.length;e++){var g=d[e];try{if(/\*/.test(g))for(var f=0;4>f;f++){var k=g.replace(/\*/g,l[f]),w=a.css(k);c.css(k,w)}else c.css(g,a.css(g))}catch(p){}}}function a(a,c,j,e){if(a.is(":visible")){var g=$.browser.msie?0:0.4;j()?(a.css("opacity",g+(e?0.2:0)),a.addClass("edit-field-overlayed"),j=a.prev(".actual-edit-overlay"),0==j.length&&(e=$.trim(a.parent().find("span.edit-field-overlay").text()),j=a.width(),g=a.height(),j=a.clone().prop("className",
"actual-edit-overlay").attr("name",null).attr("id",null).attr("disabled","disabled").css({position:"absolute",backgroundColor:"white",color:"black","-webkit-text-fill-color":"black",opacity:1,width:j,height:g}),j.is("textarea,input")?(j.val(e),d(c,j,["line-height"])):j.text(e).css("line-height",g+"px").prepend("&nbsp;"),d(c,j,["font-family","font-size","text-align"]),d(a,j,["border-*-style","border-*-color","border-*-width"]),a.css({zIndex:1,position:"relative"}),j.insertBefore(a),e=a.offset().top-
j.offset().top,0!=e&&(c=parseInt(j.css("margin-top")),e=c+e,a.is("textarea")||(e=parseInt(j.prevAll(":visible").eq(0).css("margin-bottom"))+c),j.css("margin-top",e)),a=a.offset().left-j.offset().left,0!=a&&(c=parseInt(j.css("margin-left")),j.css("margin-left",c+a)))):a.css("opacity",1).css("filter","").removeClass("edit-field-overlayed")}}function c(a,c){$(a).find("input[type='submit']").prop("disabled",c)}var f,e,g,l=["left","right","top","bottom"],k={bindMovablePopups:function(){var a=function(){f=
e=null;$("body").removeAttr("style")};$("div.popup").each(function(a,c){var d=$(c).find(".handle");d.length&&(d.css({cursor:"move"}),d.unbind("mousedown").bind("mousedown",function(a){var d=$(c).offset();e={x:d.left-a.pageX,y:d.top-a.pageY};f=$(c);d=f.offset();f.offset(d).offset(d);$("body").attr("style","cursor:move");a.preventDefault()}))});g||(g=!0,$(document).on("mousemove",function(a){f&&f.offset({top:a.pageY+e.y,left:a.pageX+e.x})}).on("keypress",a).on("mouseup",a))},genericBindOverlayEvents:function(c,
d,e){StackExchange.options.isMobile||d.bind("keydown contextmenu",function(){k.hideHelpOverlay(c)}).focus(function(){a(c,d,e,!0)}).on("blur change",function(){a(c,d,e)}).each(function(){a(c,d,e)})},bindHelpOverlayEvents:function(a){a.each(function(){var a=$(this);k.genericBindOverlayEvents(a,a,function(){return""===a.val()})})},hideHelpOverlay:function(a){a.css("opacity",1);a.css("filter","");a.removeClass("edit-field-overlayed")},onClickDraftSave:function(a){$(a).click(function(a){if(null!=StackExchange.cardiologist){a.preventDefault();
var c=this.href;StackExchange.cardiologist.ensureDraftSaved(function(){window.onbeforeunload=null;window.location.href=c});return!1}});return!0},showMessage:function(a,c,d){var e,g,f,k,a=$(a);if(a.length){d=$.extend({},{position:"inside",dismissable:!0,type:"error",closeOthers:!0},d);d.closeOthers&&$(".message").fadeOutAndRemove();var l=$('<div class="message"><div class="message-inner"><div class="message-text"></div></div></div>'),p=l.find(".message-inner"),o=l.find(".message-text");l.addClass("message-"+
d.type);o.html(c);d.dismissable&&(l.addClass("message-dismissable"),o.css("padding-right","35px"),p.prepend($("<div />",{title:"close this message (or hit Esc)","class":"message-close",text:"\u00d7"})),l.click(function(a){$(a.target).is("a")||l.fadeOutAndRemove()}));d.css&&l.css(d.css);"inside"!=d.position&&"inline"!=d.position&&!d.tip&&(d.tip=d.position.my);d.tip&&p.addClass("message-tip message-tip-"+d.tip.replace(" ","-"));if("inline"==d.position)a.append(l);else if("inside"==d.position)l.css("position",
"absolute"),a.append(l);else{l.css("position","absolute");a.offsetParent().append(l);var p=a.position(),o=a.outerWidth(!0),a=a.outerHeight(!0),r=l.outerWidth(),s=l.outerHeight();switch(d.position.at){case "top left":f=0;k=0;break;case "top center":f=0;k=o/2;break;case "top right":f=0;k=o;break;case "right top":f=0;k=o;break;case "right center":f=a/2;k=o;break;case "right bottom":f=a;k=o;break;case "bottom right":f=a;k=o;break;case "bottom center":f=a;k=o/2;break;case "bottom left":f=a;k=0;break;case "left bottom":f=
a;k=0;break;case "left center":f=a/2;k=0;break;case "left top":f=0,k=0}switch(d.position.my){case "left top":e=0;g=-9;break;case "top left":e=-9;g=0;break;case "top right":e=-9;g=r;break;case "right top":e=0;g=r+9;break;case "right bottom":e=s;g=r+9;break;case "bottom right":e=s+9;g=r;break;case "bottom left":e=s+9;g=0;break;case "left bottom":e=s,g=-9}l.css({top:p.top+f-e,left:p.left+k-g})}l.fadeIn();d.transient&&setTimeout(function(){l.fadeOutAndRemove()},Math.max(2500,40*c.length));return l}},
showErrorMessage:function(a,d,c){c=$.extend({},{position:"inside",type:"error"},c);return this.showMessage(a,d,c)},showErrorPopup:function(a,d,c){return this.showErrorMessage(a,d,c)},showInfoMessage:function(a,d,c){c=$.extend({},{position:"inside","transient":!0,type:"info"},c);return this.showMessage(a,d,c)},removeMessages:function(){$(".message").fadeOutAndRemove()},addSpinner:function(a,c){$(a).append(k.getSpinnerImg(c))},getSpinnerImg:function(a){var c=$("<img />",{"class":"ajax-loader",src:"/content/img/progress-dots.gif",
title:"loading...",alt:"loading..."});a&&c.css(a);return c},removeSpinner:function(){$("img.ajax-loader").remove()},closePopups:function(a){var c=$.Event("closePopups");c.selectorToClose=a;$(document).trigger(c)},enableSubmitButton:function(a){c(a,!1)},disableSubmitButton:function(a){c(a,!0)},loadTicks:function(a){var c;c=a?a.find(".edit-block"):$(".edit-block");0==c.find("input[name=i1l]").length&&!c.data("loading-ticks")&&(c.data("loading-ticks",!0),$.ajax({url:"/questions/ticks",cache:!1,success:function(a){c.append("<input type='hidden' name='i1l' value='"+
a+"' />")},complete:function(){c.data("loading-ticks",!1)}}))},showFancyOverlay:function(a){var a=a||{},c=$("#overlay-header"),d=a.message||"",e=$.browser.msie?{background:"#fff",opacity:0}:{};!1!==a.showClose&&(d+='<br><a class="close-overlay">close this message</a>');c.html(d).css(e).animate({opacity:"1",height:"show"},"slow",a.complete).find(".close-overlay").click(function(){c.animate({opacity:"0",height:"hide"},"fast")})},DelayedReaction:function(a,c,d){var d=d||{},e,g,f=d.always,k=function(){e=
null;a.apply(null,g)};return{trigger:function(){g=arguments;f&&f.apply(null,g);e?d.sliding&&(clearTimeout(e),e=setTimeout(k,c)):e=setTimeout(k,c)},cancel:function(){e&&(clearTimeout(e),e=null)}}},fireAndForget:function(a){$.ajax({type:"POST",url:a,async:!0})}};return k}();
function prepareEditor(d){var a=d.postfix||"",c=function(){setTimeout(function(){StackExchange.editor.initIfShown(d)},1)};if(d.onDemand){for(var f="bold-button,italic-button,spacer1,link-button,quote-button,code-button,image-button,spacer2,olist-button,ulist-button,heading-button,hr-button,spacer3,undo-button,redo-button".split(","),e=$('<ul id="wmd-button-row'+a+'" class="wmd-button-row" />').appendTo(".wmd-button-bar"),g=0,l=0;l<f.length;l++){var k=f[l],h=/spacer/.test(k),k=$("<li id='wmd-"+k+a+
"' />").prop("className","wmd-"+(h?"spacer":"button")).css("left",25*l).appendTo(e);$("<span />").css("background-position",g+"px -20px").appendTo(k);h||(g-=20)}var n=!1;$("#wmd-input, #title, #tagnames, #edit-comment, #m-address, #display-name").one("focus click keydown",function(){n||(n=!0,e.addSpinner({"float":"right"}),StackExchange.using("editor",function(){e.remove();d.autoShowMarkdownHelp&&(d.immediatelyShowMarkdownHelp=!0);c()}))})}else StackExchange.using("editor",c)}
StackExchange.switchMobile=function(d,a){$.post("/mobile/"+d,{returnurl:a},function(a){window.location=a})};StackExchange.switchLocale=function(d,a){$.post("/locale/"+d,{returnurl:a},function(a){window.location=a})};
jQuery.cookie=function(d,a,c){if("undefined"!=typeof a){c=c||{};null===a&&(a="",c.expires=-1);var f="";if(c.expires&&("number"==typeof c.expires||c.expires.toUTCString))"number"==typeof c.expires?(f=new Date,f.setTime(f.getTime()+864E5*c.expires)):f=c.expires,f="; expires="+f.toUTCString();var e=c.path?"; path="+c.path:"",g=c.domain?"; domain="+c.domain:"",c=c.secure?"; secure":"";document.cookie=[d,"=",encodeURIComponent(a),f,e,g,c].join("")}else{a=null;if(document.cookie&&""!=document.cookie){c=
document.cookie.split(";");for(f=0;f<c.length;f++)if(e=jQuery.trim(c[f]),e.substring(0,d.length+1)==d+"="){a=decodeURIComponent(e.substring(d.length+1));break}}return a}};jQuery.expr[":"].regex=function(d,a,c){var a=c[3].split(","),f=/^(data|css):/,c=a[0].match(f)?a[0].split(":")[0]:"attr",f=a.shift().replace(f,"");return RegExp(a.join("").replace(/^\s+|\s+$/g,""),"ig").test(jQuery(d)[c](f))};
$.extend($.expr[":"],{containsExact:function(d,a,c){return $.trim(d.innerHTML.toLowerCase())===c[3].toLowerCase()},containsExactCase:function(d,a,c){return $.trim(d.innerHTML)===c[3]},containsRegex:function(d,a,c){a=/^\/((?:\\\/|[^\/])+)\/([mig]{0,3})$/.exec(c[3]);return RegExp(a[1],a[2]).test($.trim(d.innerHTML))}});
$.extend({URLEncode:function(d){for(var a="",c=0,d=d.toString(),f=/(^[a-zA-Z0-9_.]*)/;c<d.length;){var e=f.exec(d.substr(c));null!=e&&1<e.length&&""!=e[1]?(a+=e[1],c+=e[1].length):(" "==d[c]?a+="+":(e=d.charCodeAt(c).toString(16),a+="%"+(2>e.length?"0":"")+e.toUpperCase()),c++)}return a},URLDecode:function(d){for(var a,c=/(%[^%]{2})/;null!=(m=c.exec(d))&&1<m.length&&""!=m[1];)b=parseInt(m[1].substr(1),16),a=String.fromCharCode(b),d=d.replace(m[1],a);return d}});
(function(d){d.fn.typeWatch=function(a){function c(a){if("TEXT"==a.type.toUpperCase()||"TEXTAREA"==a.nodeName.toUpperCase()){var c={timer:null,text:d(a).val().toUpperCase(),cb:f.callback,el:a,wait:f.wait};f.highlight&&d(a).focus(function(){this.select()});var l=function(a){var e=c.wait,l=!1;13==a.keyCode&&"TEXT"==this.type.toUpperCase()&&(e=1,l=!0);clearTimeout(c.timer);c.timer=setTimeout(function(){var a=l,e=d(c.el).val();if(e.length>f.captureLength&&e.toUpperCase()!=c.text||a&&e.length>f.captureLength)c.text=
e.toUpperCase(),c.cb(e)},e)};d(a).keydown(l).bind("paste",null,function(a){a.which||l(this)}).bind("input",null,function(a){a.which||l(this)})}}var f=d.extend({wait:750,callback:function(){},highlight:!0,captureLength:2},a);return this.each(function(){c(this)})}})(jQuery);
(function(d){function a(a){var e;return a&&a.constructor==Array&&3==a.length?a:(e=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/.exec(a))?[parseInt(e[1]),parseInt(e[2]),parseInt(e[3])]:(e=/rgb\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*\)/.exec(a))?[2.55*parseFloat(e[1]),2.55*parseFloat(e[2]),2.55*parseFloat(e[3])]:(e=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/.exec(a))?[parseInt(e[1],16),parseInt(e[2],16),parseInt(e[3],16)]:
(e=/#([a-fA-F0-9])([a-fA-F0-9])([a-fA-F0-9])/.exec(a))?[parseInt(e[1]+e[1],16),parseInt(e[2]+e[2],16),parseInt(e[3]+e[3],16)]:/rgba\(0, 0, 0, 0\)/.exec(a)?c.transparent:c[d.trim(a).toLowerCase()]}d.each("backgroundColor,borderBottomColor,borderLeftColor,borderRightColor,borderTopColor,color,outlineColor".split(","),function(c,e){d.fx.step[e]=function(c){if(!c.colorInit){var f;f=c.elem;var k=e,h;do{h=d.curCSS(f,k);if(""!=h&&"transparent"!=h||d.nodeName(f,"body"))break;k="backgroundColor"}while(f=f.parentNode);
f=a(h);c.start=f;c.end=a(c.end);c.colorInit=!0}c.elem.style[e]="rgb("+[Math.max(Math.min(parseInt(c.pos*(c.end[0]-c.start[0])+c.start[0]),255),0),Math.max(Math.min(parseInt(c.pos*(c.end[1]-c.start[1])+c.start[1]),255),0),Math.max(Math.min(parseInt(c.pos*(c.end[2]-c.start[2])+c.start[2]),255),0)].join()+")"}});var c={transparent:[255,255,255]}})(jQuery);
StackExchange.gps=function(){StackExchange._gps_track=[];return{track:function(d,a){var a=a||{},c=null;StackExchange.options&&StackExchange.options.user&&(a.user_type=StackExchange.options.user.userType,c=StackExchange.options.user.ab);var f={evt:d,properties:a,now:(new Date).getTime()};c&&(f.ab=c);StackExchange._gps_track.push(f)}}}();