/* include file for GRID1 */

#define     ID_LAB1     255
#define     ID_CHILD1   256
#define     ID_CHILD2   257
#define     ID_CHILD3   258

#define IDM_VIEW          1
#define IDM_RLC           2
#define IDM_NETPARM       3
#define IDM_FILESYS       4
#define IDM_LOADIMAGE     5
#define IDM_SAVELOG       6
#define IDM_EXITNOW       7

#define IDM_EDITOR        8
#define IDM_CLEARGRID     9
#define IDM_NEWCHAR      10
#define IDM_COLORS       11
#define IDM_WININFO      12
#define IDM_GRIDINFO     13
        

#define IDM_ENTFIELD    100
#define IDM_BUTTOK      101
#define IDM_BUTTCAN     102


#define IDD_COLORS       200
#define IDD_FCLRBLUE     201
#define IDD_FCLRRED      202
#define IDD_FCLRPINK     203
#define IDD_FCLRGREEN    204
#define IDD_FCLRCYAN     205
#define IDD_FCLRYELLOW   206
#define IDD_FCLRDKGRAY   208
#define IDD_FCLRDKBLUE   209
#define IDD_FCLRDKRED    210
#define IDD_FCLRDKPINK   211
#define IDD_FCLRDKGREEN  212
#define IDD_FCLRDKCYAN   213
#define IDD_FCLRDKBROWN  214
#define IDD_FCLRPLGRAY   215
#define IDD_FCLRNEUTRAL  207

#define IDD_BCOLORS      300
#define IDD_BCLRBLUE     301
#define IDD_BCLRRED      302
#define IDD_BCLRPINK     303
#define IDD_BCLRGREEN    304
#define IDD_BCLRCYAN     305
#define IDD_BCLRYELLOW   306
#define IDD_BCLRDKGRAY   308
#define IDD_BCLRDKBLUE   309
#define IDD_BCLRDKRED    310
#define IDD_BCLRDKPINK   311
#define IDD_BCLRDKGREEN  312
#define IDD_BCLRDKCYAN   313
#define IDD_BCLRDKBROWN  314
#define IDD_BCLRPLGRAY   315
#define IDD_BCLRBKGRND   300
        
#define IDD_NETFILE      316
#define IDD_FLEDIT       317
#define IDD_FLIST        318

#define IDD_ASCIIDLG     319
#define IDD_ASCIIEDIT    320
#define IDD_ASCIILIST    321
#define IDD_UPPERCASE    322
#define IDD_LOWERCASE    323
#define IDD_DIGITS09     324

#define DLG_OK           400
#define DLG_CANCEL       401
        
        
#define WM_USER1         WM_USER+1
#define WM_USER2         WM_USER+2
#define WM_USER3         WM_USER+3
        
