# Generated automatically from Makefile.in by configure.
# Main libs Makefile
# $Id: Makefile,v 1.34 2002/09/23 15:16:32 rjs Exp $

# keep the order, some libs have to be build before others
# PDU not yet working => MAKEOPT -i
include ../config/mkcommon.inc

MAKEOPT	= -i
SUB_DIRS = $(LIBTARGETS)

include ../config/mksubdirs.inc
