if("undefined"==typeof SD||!SD)var SD={};SD.config={adhost:"http://ysm.sitemaji.com/",statichost:"http://ad.sitemaji.com/",dr:{source:"eyny",pixel:"1310888"},sitename:"ov_test"};
(function(){SD.util=SD.util||{};S=SD.util;SD.util.Dom={_reClassNameCache:{},_getClassRegEx:function(b){var e=S.Dom._reClassNameCache[b];e||(e=RegExp("(?:^|\\s+)"+b+"(?:\\s+|$)"),S.Dom._reClassNameCache[b]=e);return e},hasClass:function(b,e){if("undefined"==typeof b||null==b||!RegExp)return!1;var a=RegExp("(^|\\s)"+e+"(\\s|$)");return"string"==typeof b?a.test(b):"object"==typeof b&&b.className?a.test(b.className):!1},getElementsByClassName:function(b,e,a,c){for(var d=[],e=(a||document).getElementsByTagName(e||
"*"),b=S.Dom._getClassRegEx(b),a=0,f=e.length;a<f;a++)b.test(e[a].className)&&(d[d.length]=e[a],c&&c.call(e[a],e[a]));return d},getAncestorByTagName:function(b,e){for(;b=b.parentNode;)if(b.tagName.toLowerCase()==e)return b;return null}};SD.util.Event={getTarget:function(b){return this.resolveTextNode(b.target||b.srcElement)},resolveTextNode:function(b){try{if(b&&3==b.nodeType)return b.parentNode}catch(e){}return b},preventDefault:function(b){b.preventDefault?b.preventDefault():b.returnValue=!1}}})();
(function(){var b=SD.util.Dom;SD.util.createEl={get:function(b,a,c){var b=document.createElement(b),d;for(d in a)b[d]=a[d];c&&(b.innerHTML=c);this.append(b);return b},append:function(b){(document.getElementsByTagName("head")[0]||document.body).appendChild(b)},remove:function(b){setTimeout(function(){b.parentNode.removeChild(b);b=null},0)},js:function(b,a){var c=this.get("script",{src:b,type:"text/javascript"},null);a&&c.setAttribute("charset",a);return c},css:function(b,a){a||(a="all");return this.get("link",
{href:b,rel:"stylesheet",type:"text/css",media:a},null,"head")},adtemplate:function(e,a,c){a.className=a.className||SD.config.prefix;document.write('<div class="'+a.className+'" style="display:none;"></div>');e=b.getElementsByClassName(a.className);e=e[e.length-1];c&&(e.innerHTML=c);return e}}})();
(function(){var b=SD.util,e=document.getElementsByTagName("head")[0];SD.util.JSONP=SD.util.JSONP||{_oRequests:{},request:function(a){var c="req_"+(new Date).getTime(),d={};d.sRequestId=c;d.callback=function(a){b.JSONP.callback(c,a)};d.realCallback=a.callback;d.onTimeout=a.onTimeout;a.callback="SD.util.JSONP._oRequests."+c+".callback";-1==a.url.indexOf("?")&&(a.url+="?");var f="";""==f&&(f+="&");f+="callback="+a.callback;a.url+=f;f=document.createElement("script");d.script=f;f.setAttribute("src",a.url);
f.setAttribute("type","text/javascript");d.timeout=setTimeout(function(){b.JSONP.timeoutClear(c)},5E3);e.appendChild(f);b.JSONP._oRequests[c]=d},callback:function(a,c){var d=b.JSONP._oRequests[a];d&&clearTimeout(d.timeout);d.realCallback(c);delete b.JSONP._oRequests[a]},timeoutClear:function(a){var c=b.JSONP._oRequests[a];if(c){var d={};d.sRequestId=c.sRequestId;d.oConfig={};for(var e in c.oConfig)d.oConfig[e]=c.oConfig[e];e=c.onTimeout;delete c[a];e&&e(d)}}}})();
(function(){var b=SD.util.Dom.getElementsByClassName("sitemajidr");SD.util.ysm={drHTML:function(b,a,c){return"<IFRAME FRAMEBORDER=0 MARGINWIDTH=0 MARGINHEIGHT=0 SCROLLING=NO WIDTH="+a+" HEIGHT="+c+' SRC="http://ad.yieldmanager.com/st?ad_type=iframe&ad_size='+a+"x"+c+"&entity=376336&site_code="+b+"&section_code=game&ytwpartcode="+b+'"></IFRAME>'},drgen:function(){if(b[0])for(var e=0,a=b.length;e<a;e++){var c=b[e],d=(c.getAttribute("model")?c.getAttribute("model"):"300x250").split("x");c.innerHTML=
this.drHTML(SD.config.dr.source,d[0]?d[0]:"300",d[1]?d[1]:"250")}}}})();
(function(){for(var b=SD.util.Dom,e=SD.util.Event,a=function(b){try{return b.replace(/^\s+|\s+$/g,"")}catch(a){return b}},c=b.getElementsByClassName("sitemajiad"),d=b.getElementsByClassName("sitemajidr"),f=0,h=0,m=c.length;h<m;h++)var n=parseInt(c[h].getAttribute("model")),f=f+n;d[0]&&SD.util.ysm.drgen();if(c[0]){sRef=document.referrer?document.referrer:"";sPmID="undefined"!=typeof pmid?pmid:"tw_syndication_sitetag_eyny_pm";sCmID="undefined"!=typeof cmid?cmid:"tw_syndication_sitetag_eyny_cm";sCmtxt=
"undefined"!=typeof ctxtID?ctxtID:"tw_syndication_sitetag_game_001";sMax="undefined"!=typeof f?parseInt(f):3;sFor="undefined"!=typeof fip?fip:"";sIp="undefined"!=typeof ip?ip:"";sType="undefined"!=typeof adType?adType:"pm";sTitle=a(document.title.toString().split("-")[0]);c="";(d=b.getElementsByClassName("firstpost")[0])?(c+=a(d.innerHTML).replace(/(&nbsp;)|(&ensp;)|(&emsp;)/g,"").replace(/\s*/g,"").replace(/<[^>].*?>/g,""),c=(sTitle+c).substr(0,170)):c=sTitle.substr(0,170);d="";if(f=document.getElementById("srchtxt"))d=
a(f.value),"\u641c\u5c0b\u6b64\u7248\u4e3b\u984c"==d&&(d="");var q=0,k=[],a=document.location.toString();S.createEl.css(SD.config.statichost+"eyny.css","screen");var j={agent:encodeURIComponent(navigator.userAgent.toLowerCase()),maxCount:sMax,searchkey:d,cmid:sCmID,pmid:sPmID,ctxtID:sCmtxt,type:sType,content:encodeURIComponent(c),refurl:encodeURIComponent(sRef),url:encodeURIComponent(a)};aData=[];var o=0;for(h in j)aData[aData.length]=h+"="+j[h];h={url:SD.config.adhost+SD.config.sitename+".php?"+
aData.join("&"),callback:function(a){if(a.length>0){c=0;for(d=a.length;c<d;c++){k[o]='<dl class="sitemaji-u" onclick="window.open(\''+a[c].ClickUrl+'\');"><dt class="sitemaji-g"><a class="sitemaji-u aposted" target="_blank" href="http://'+a[c].siteHost+'">'+a[c].title+'</a><address class="sitemaji-u">'+a[c].siteHost+"</address></dt><dd>"+a[c].description+"</dd></dl>";o++}}if(k.length<sMax){q=sMax-a.length;j.maxCount=q;j.type="cm";aData=[];for(var c in j)aData[aData.length]=c+"="+j[c];c={url:SD.config.adhost+
SD.config.sitename+".php?"+aData.join("&"),callback:function(a){if(a.length>0){c=0;for(d=a.length;c<d;c++){k[o]='<dl class="sitemaji-u" onclick="window.open(\''+a[c].ClickUrl+'\');"><dt class="sitemaji-g"><a class="sitemaji-u aposted" target="_blank" href="http://'+a[c].siteHost+'">'+a[c].title+'</a><address class="sitemaji-u">'+a[c].siteHost+"</address></dt><dd>"+a[c].description+"</dd></dl>";o++}}for(var a=b.getElementsByClassName("sitemajiad"),c=0,d=a.length;c<d;c++){for(var f=a[c],h=f.getAttribute("model"),
h=h?h:3,g="",i=0,j=parseInt(h);i<j;i++){i==0&&(g='<div class="bd sitemajiad-g">'+g);k.length>0&&(g=g+k.shift());i==h-1&&(g=g!=='<div class="bd sitemajiad-g">'?g+'</div><div class="ft"><cite>&#36106;&#21161;&#32178;&#31449;</cite></div>':g+"</div>")}f.innerHTML=g;if(b.hasClass(f,"photo")||b.hasClass(f,"sitemaji-photo")){h=f.getElementsByTagName("dl");i=0;for(j=h.length;i<j;i++){var g=h[i],m=g.getElementsByTagName("address")[0],n=g.getElementsByTagName("dt")[0],l=document.createElement("img");l.src=
"http://open.thumbshots.org/image.aspx?url="+m.innerHTML;g.insertBefore(l,n);l=null}}f.onclick=function(a){a=a||window.event;e.preventDefault(a)}}}};SD.util.JSONP.request(c)}else{a=b.getElementsByClassName("sitemajiad");c=0;for(var d=a.length;c<d;c++){for(var f=a[c],h=f.getAttribute("model"),h=h?h:3,g="",i=0,l=parseInt(h);i<l;i++){i==0&&(g='<div class="bd sitemajiad-g">'+g);k.length>0&&(g=g+k.shift());i==h-1&&(g=g!=='<div class="bd sitemajiad-g">'?g+'</div><div class="ft"><cite>&#36106;&#21161;&#32178;&#31449;</cite></div>':
g+"</div>")}f.innerHTML=g;if(b.hasClass(f,"photo")||b.hasClass(f,"sitemaji-photo")){h=f.getElementsByTagName("dl");i=0;for(l=h.length;i<l;i++){var g=h[i],m=g.getElementsByTagName("address")[0],n=g.getElementsByTagName("dt")[0],p=document.createElement("img");p.src="http://open.thumbshots.org/image.aspx?url="+m.innerHTML;g.insertBefore(p,n);p=null}}f.onclick=function(a){a=a||window.event;e.preventDefault(a)}}}}};SD.util.JSONP.request(h)}})();
