document.write("<html>");
document.write("<head>");
document.write("<title>Untitled Document</title>");
document.write("<meta http-equiv='Content-Type' content='text/html; charset=gb2312'>");
document.write("<link rel='stylesheet' href='/cpcw.css'>");
document.write("</head>");
document.write("");
document.write("<body bgcolor='#FFFFFF' leftmargin='0' topmargin='0' marginwidth='0' marginheight='0'>");
document.write("<table width='135' border='0' cellspacing='0'>");
document.write("  <tr> ");
document.write("    <td><a href='/backup/it/index.htm' target='_blank' class='unnamed3'>第二届全国IT技能大赛</a></td>");
document.write("  </tr>");
document.write("  <tr> ");
document.write("    <td><span class='b1'><a href='/message/m_12.htm' target='_blank'>软考成就程序人生梦想</a></span></td>");
document.write("  </tr>");
document.write("  <tr> ");
document.write("    <td><a href='http://training.yesky.com/once/demo.htm' target='_blank'>免费试学天极网校课程</a></td>");
document.write("  </tr>");
document.write("  <tr> ");
document.write("    <td><a href='http://training.yesky.com/exam/index.htm' target='_blank'><font color='#FF0000'>认证资讯全新改版</font></a></td>");
document.write("  </tr>");
document.write("  <tr> ");
document.write("    <td><a href='/recommend/rec7.htm'></a><a href='http://training.yesky.com/topic/softtopic/INDEX.HTM' target='_blank'>3000元大奖助您程考冲刺</a></td>");
document.write("  </tr>");
document.write("</table>");
document.write("</body>");
document.write("</html>");
