
document.write("<table width='100%' border='0' cellspacing='0' cellpadding='2'>");
document.write("<tr>");
document.write("<td width='12'>·</td>");
document.write("<td><a href=http://adv.chinabyte.com/hit/hit.jsp?id=1912&url=http%3A%2F%2Fwww.ms-hardware.com%2Fie4%2Fflash.html target=_blank><font color=ff000>参加游戏活动，获取全新IE4.0</font></a></td>");
document.write("<td width='12'>·</td>");
document.write("<td><a href=http://adv.chinabyte.com/hit/hit.jsp?id=1871&url=http%3A%2F%2Fad.www.net.cn%2Fad%2Fchinabyte%2Fchinabyte_textlink_index.htm target=_blank>网络英雄，网上留名</a></td>");
document.write("</tr>");
document.write("<tr>");
document.write("<td width='12'>·</td>");
document.write("<td><a href=http://adv.chinabyte.com/hit/hit.jsp?id=1954&url=http%3A%2F%2Fwww.bea.com.cn%2Fbea_dev2devdays2004%2Findex.html target=_blank>BEA千人盛宴免费注册</a></td>");
document.write("<td width='12'>·</td>");
document.write("<td><a href=http://adv.chinabyte.com/hit/hit.jsp?id=1631&url=http%3A%2F%2Fwww.cisco.com%2Fcn%2Fpower%2Fstorage%2Fstorageday.shtml%3F%26pnBAC%3DBAC-1214 target=_blank>揭开存储网络根源问题</a></td>");
document.write("</tr>");
document.write("<tr>");
document.write("<td width='12'>·</td>");
document.write("<td><a href=http://adv.chinabyte.com/hit/hit.jsp?id=1664&url=http%3A%2F%2F203.81.25.186%2Fjiayong%2Fnotebook%2F%3Fwodoopro%3Dyeskyhomepagefull target=_blank>双重惊喜礼券，1元体验1000天</a></td>");
document.write("<td width='12'>·</td>");
document.write("<td><a href=http://adv.chinabyte.com/hit/hit.jsp?id=1951&url=http%3A%2F%2Fwww.wish-edu.com target=_blank>点击威迅教育，择业不再迷茫</a></td>");
document.write("</tr>");
document.write("<tr>");
document.write("<td width='12'>·</td>");
document.write("<td><a href=http://adv.chinabyte.com/hit/hit.jsp?id=1884&url=http%3A%2F%2Fwww.moup.cn%2Fad%2Fad2.htm target=_blank>免费试用灵信网站</a></td>");
document.write("<td width='12'>·</td>");
document.write("<td><a href=http://adv.chinabyte.com/hit/hit.jsp?id=1916&url=http%3A%2F%2Fcn.rd.yahoo.com%2Fauct%2Fhp%2Fwest%2Fpromo%2Fevt%3D26508%2F*http%3A%2F%2Fcn.promo.yahoo.com%2Fauction%2F200408%2Fchoujiang%2Findex.html target=_blank><font color=ff000>百万礼品赠送</font></a></td>");
document.write("</tr>");
document.write("</table>");