cpp2html SortableStringArray.h>SortableStringArray_H.html
cpp2html SortableStringArray.cpp >SortableStringArray_CPP.html
cpp2html CStringArray_Sort.cpp >CStringArray_Sort_CPP.html
cpp2html CStringArray_Sort.h >CStringArray_Sort_H.html