# PDFlib bindings Makefile
# $Id: Makefile,v 1.6.2.1 2004/12/09 23:30:19 rjs Exp $

include ../../config/mkcommon.inc

SUB_DIRS =  $(BINDINGS)

include ../../config/mksubdirs.inc


clean::
	$(RM) php/smoke_c*.trace php/smoke_c*.pdf
	$(RM) rpg/smoke_c*.trace rpg/smoke_c*.pdf
